/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jdBuscaAgendamento.java
 *
 * Created on 02/02/2010, 09:10:34
 */
package visual;

import controlador.*;
import dao.DAO;
import java.awt.Image;
import java.awt.Toolkit;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import modelo.Aluno;

/**
 *
 * @author luizam
 */
public class jdBuscaAluno extends javax.swing.JDialog {

    private static ControleVersao versao = new ControleVersao();
    private DAO dao;
    private Aluno aluno;
    private Formatos formatos = new Formatos();
    private ClasseGeral classeGeral;
    private ControleImagem controleImagem = new ControleImagem();
    private EditaOrdemTabela editaOrdemTabela;

    private String tipoCadastro = "";
    private String tipoCadastroUsuario;
    private String modalidade = "";
    private boolean imprimirTodos = false;

    /** Creates new form jdBuscaAgendamento */
    public jdBuscaAluno(java.awt.Frame parent, boolean modal) {
        super(parent, "Buscar Aluno - " + versao.getVersao() + " - " + versao.getAno(), modal);
        initComponents();

        //Altera icone na barra de titulo
        Toolkit kit = Toolkit.getDefaultToolkit();
        Image img = kit.getImage(controleImagem.getIconeImagem());
        this.setIconImage(img);

        //maximiza tela
        //this.setExtendedState(MAXIMIZED_BOTH);

        //centraliza tela
        setSize(getWidth(), getHeight());
        setLocationRelativeTo(null);

        try {
            jftfBuscaCpfMae.setFormatterFactory(formatos.getFormatoCpf());
            jftfBuscaCpfPai.setFormatterFactory(formatos.getFormatoCpf());
        } catch (ParseException ex) {
            Logger.getLogger(jfCadastroCmei.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Não foi possivel formatar campos de CPF, \n Contate o Administrador!", "Erro", 0, null);
        }

        setNumeroCaracteres();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgTipoCadastro = new javax.swing.ButtonGroup();
        btgModalidade = new javax.swing.ButtonGroup();
        jpBotoes = new javax.swing.JPanel();
        jbBuscaFechar = new javax.swing.JButton();
        jbBuscaEnviarDados = new javax.swing.JButton();
        jbBuscaCancelar = new javax.swing.JButton();
        jbBuscaPesquisar = new javax.swing.JButton();
        jpBuscaAluno = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbBuscaAluno = new javax.swing.JTable();
        jtfBuscaNomeAluno = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jcbBuscaNomeEntidade = new javax.swing.JComboBox();
        jtfBuscaMatricula = new javax.swing.JTextField();
        jtfBuscaFiliacaoPai = new javax.swing.JTextField();
        jtfBuscaFiliacaoMae = new javax.swing.JTextField();
        jftfBuscaCpfPai = new javax.swing.JFormattedTextField();
        jftfBuscaCpfMae = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jrbFilaEspera = new javax.swing.JRadioButton();
        jrbMatriculado = new javax.swing.JRadioButton();
        jrbAmbos = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jrbModalidadeTodas = new javax.swing.JRadioButton();
        jrbModalidadeBercario = new javax.swing.JRadioButton();
        jrbModalidadeMaternal1 = new javax.swing.JRadioButton();
        jrbModalidadeMaternal2 = new javax.swing.JRadioButton();
        jrbModalidadePre1 = new javax.swing.JRadioButton();
        jrbModalidadePre2 = new javax.swing.JRadioButton();
        jrbDesistencia = new javax.swing.JRadioButton();
        jrbEgresso = new javax.swing.JRadioButton();
        jrbTransferencia = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jlbTotalAlunos = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jlbTotalBuscadoTabela = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jpBotoes.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());

        jbBuscaFechar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbBuscaFechar.setText("Fechar");
        jbBuscaFechar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbBuscaFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscaFecharActionPerformed(evt);
            }
        });

        jbBuscaEnviarDados.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbBuscaEnviarDados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Enviar.png"))); // NOI18N
        jbBuscaEnviarDados.setText("Enviar Dados");
        jbBuscaEnviarDados.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbBuscaEnviarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscaEnviarDadosActionPerformed(evt);
            }
        });

        jbBuscaCancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbBuscaCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jbBuscaCancelar.setText("Cancelar");
        jbBuscaCancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbBuscaCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscaCancelarActionPerformed(evt);
            }
        });

        jbBuscaPesquisar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbBuscaPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jbBuscaPesquisar.setText("Pesquisar");
        jbBuscaPesquisar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbBuscaPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscaPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpBotoesLayout = new javax.swing.GroupLayout(jpBotoes);
        jpBotoes.setLayout(jpBotoesLayout);
        jpBotoesLayout.setHorizontalGroup(
            jpBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBotoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbBuscaPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbBuscaCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbBuscaEnviarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbBuscaFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpBotoesLayout.setVerticalGroup(
            jpBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbBuscaFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscaEnviarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscaCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscaPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpBuscaAluno.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nome Aluno: ");

        jtbBuscaAluno.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jtbBuscaAluno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtbBuscaAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ordem", "Nome do Aluno", "Filiação Pai/Mãe", "CPF Pai/Mãe", "CMEI", "Data Nascimento", "Data Cadastro", "Modalidade", "Status Cadastro", "Matrícula", "Código"
            }
        ));
        jtbBuscaAluno.setGridColor(new java.awt.Color(204, 204, 204));
        jtbBuscaAluno.setRowHeight(19);
        jtbBuscaAluno.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtbBuscaAluno.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtbBuscaAluno);

        jtfBuscaNomeAluno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfBuscaNomeAluno.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jtfBuscaNomeAluno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfBuscaNomeAlunoFocusLost(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Matrícula: ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Filiação Pai: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("CPF da Mãe: ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Nome do CMEI: ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Filicação Mãe: ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("CPF do Pai: ");

        jcbBuscaNomeEntidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbBuscaNomeEntidade.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtfBuscaMatricula.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfBuscaMatricula.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jtfBuscaMatricula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfBuscaMatriculaFocusLost(evt);
            }
        });

        jtfBuscaFiliacaoPai.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfBuscaFiliacaoPai.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jtfBuscaFiliacaoPai.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfBuscaFiliacaoPaiFocusLost(evt);
            }
        });

        jtfBuscaFiliacaoMae.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfBuscaFiliacaoMae.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jtfBuscaFiliacaoMae.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfBuscaFiliacaoMaeFocusLost(evt);
            }
        });

        jftfBuscaCpfPai.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jftfBuscaCpfPai.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jftfBuscaCpfMae.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jftfBuscaCpfMae.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Status Cadastro: ");

        btgTipoCadastro.add(jrbFilaEspera);
        jrbFilaEspera.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jrbFilaEspera.setText("Fila de Espera");
        jrbFilaEspera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbFilaEsperaActionPerformed(evt);
            }
        });

        btgTipoCadastro.add(jrbMatriculado);
        jrbMatriculado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jrbMatriculado.setText("Matriculado");
        jrbMatriculado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbMatriculadoActionPerformed(evt);
            }
        });

        btgTipoCadastro.add(jrbAmbos);
        jrbAmbos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jrbAmbos.setSelected(true);
        jrbAmbos.setText("Ambos");
        jrbAmbos.setToolTipText("Ambos serve apenas para Fila e Matricula!");
        jrbAmbos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbAmbosActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Modalidade: ");

        btgModalidade.add(jrbModalidadeTodas);
        jrbModalidadeTodas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jrbModalidadeTodas.setSelected(true);
        jrbModalidadeTodas.setText("Todas");
        jrbModalidadeTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbModalidadeTodasActionPerformed(evt);
            }
        });

        btgModalidade.add(jrbModalidadeBercario);
        jrbModalidadeBercario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jrbModalidadeBercario.setText("Berçário");
        jrbModalidadeBercario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbModalidadeBercarioActionPerformed(evt);
            }
        });

        btgModalidade.add(jrbModalidadeMaternal1);
        jrbModalidadeMaternal1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jrbModalidadeMaternal1.setText("Maternal I");
        jrbModalidadeMaternal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbModalidadeMaternal1ActionPerformed(evt);
            }
        });

        btgModalidade.add(jrbModalidadeMaternal2);
        jrbModalidadeMaternal2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jrbModalidadeMaternal2.setText("Maternal II");
        jrbModalidadeMaternal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbModalidadeMaternal2ActionPerformed(evt);
            }
        });

        btgModalidade.add(jrbModalidadePre1);
        jrbModalidadePre1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jrbModalidadePre1.setText("Pré I");
        jrbModalidadePre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbModalidadePre1ActionPerformed(evt);
            }
        });

        btgModalidade.add(jrbModalidadePre2);
        jrbModalidadePre2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jrbModalidadePre2.setText("Pré II");
        jrbModalidadePre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbModalidadePre2ActionPerformed(evt);
            }
        });

        btgTipoCadastro.add(jrbDesistencia);
        jrbDesistencia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jrbDesistencia.setText("Desistência");
        jrbDesistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbDesistenciaActionPerformed(evt);
            }
        });

        btgTipoCadastro.add(jrbEgresso);
        jrbEgresso.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jrbEgresso.setText("Egresso");
        jrbEgresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbEgressoActionPerformed(evt);
            }
        });

        btgTipoCadastro.add(jrbTransferencia);
        jrbTransferencia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jrbTransferencia.setText("Transferência");
        jrbTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbTransferenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpBuscaAlunoLayout = new javax.swing.GroupLayout(jpBuscaAluno);
        jpBuscaAluno.setLayout(jpBuscaAlunoLayout);
        jpBuscaAlunoLayout.setHorizontalGroup(
            jpBuscaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBuscaAlunoLayout.createSequentialGroup()
                .addGroup(jpBuscaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpBuscaAlunoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jpBuscaAlunoLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jpBuscaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpBuscaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpBuscaAlunoLayout.createSequentialGroup()
                                .addGroup(jpBuscaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpBuscaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jtfBuscaFiliacaoPai, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jcbBuscaNomeEntidade, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtfBuscaFiliacaoMae, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jpBuscaAlunoLayout.createSequentialGroup()
                                            .addComponent(jtfBuscaNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtfBuscaMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpBuscaAlunoLayout.createSequentialGroup()
                                            .addComponent(jftfBuscaCpfPai, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jftfBuscaCpfMae, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jpBuscaAlunoLayout.createSequentialGroup()
                                        .addComponent(jrbModalidadeTodas)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jrbModalidadeBercario)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jrbModalidadeMaternal1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jrbModalidadeMaternal2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jrbModalidadePre1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jrbModalidadePre2)))
                                .addGap(0, 300, Short.MAX_VALUE))
                            .addGroup(jpBuscaAlunoLayout.createSequentialGroup()
                                .addComponent(jrbFilaEspera)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrbMatriculado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrbTransferencia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrbAmbos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrbDesistencia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrbEgresso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jpBuscaAlunoLayout.setVerticalGroup(
            jpBuscaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBuscaAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBuscaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcbBuscaNomeEntidade, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpBuscaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfBuscaNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jtfBuscaMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpBuscaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfBuscaFiliacaoPai, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpBuscaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfBuscaFiliacaoMae, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpBuscaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jftfBuscaCpfPai, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jftfBuscaCpfMae, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpBuscaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jrbFilaEspera)
                    .addComponent(jrbMatriculado)
                    .addComponent(jrbAmbos)
                    .addComponent(jrbDesistencia)
                    .addComponent(jrbEgresso)
                    .addComponent(jrbTransferencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpBuscaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jrbModalidadeTodas)
                    .addComponent(jrbModalidadeBercario)
                    .addComponent(jrbModalidadeMaternal1)
                    .addComponent(jrbModalidadeMaternal2)
                    .addComponent(jrbModalidadePre1)
                    .addComponent(jrbModalidadePre2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Total Alunos: ");

        jlbTotalAlunos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlbTotalAlunos.setText("0");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Total Buscado na Tabela: ");

        jlbTotalBuscadoTabela.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlbTotalBuscadoTabela.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbTotalAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbTotalBuscadoTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(jlbTotalBuscadoTabela))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jlbTotalAlunos)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBuscaAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpBuscaAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        fechar();
    }//GEN-LAST:event_formWindowClosing

    private void jbBuscaFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscaFecharActionPerformed
        fechar();
    }//GEN-LAST:event_jbBuscaFecharActionPerformed

    private void jbBuscaPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscaPesquisarActionPerformed
        pesquisar();
    }//GEN-LAST:event_jbBuscaPesquisarActionPerformed

    private void jbBuscaCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscaCancelarActionPerformed
        cancelar();
    }//GEN-LAST:event_jbBuscaCancelarActionPerformed

    private void jbBuscaEnviarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscaEnviarDadosActionPerformed
        buscaDados();
        fechar();
    }//GEN-LAST:event_jbBuscaEnviarDadosActionPerformed

    private void jrbAmbosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbAmbosActionPerformed

        if (jrbAmbos.isSelected()) {
            tipoCadastro = "";
        }

    }//GEN-LAST:event_jrbAmbosActionPerformed

    private void jrbMatriculadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMatriculadoActionPerformed

        if (jrbMatriculado.isSelected()) {
            tipoCadastro = "TR";
        }

    }//GEN-LAST:event_jrbMatriculadoActionPerformed

    private void jrbFilaEsperaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbFilaEsperaActionPerformed

        if (jrbFilaEspera.isSelected()) {
            tipoCadastro = "FILA";
        }

    }//GEN-LAST:event_jrbFilaEsperaActionPerformed

    private void jtfBuscaNomeAlunoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfBuscaNomeAlunoFocusLost
        jtfBuscaNomeAluno.setText(jtfBuscaNomeAluno.getText().toUpperCase());
    }//GEN-LAST:event_jtfBuscaNomeAlunoFocusLost

    private void jtfBuscaMatriculaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfBuscaMatriculaFocusLost
        ClasseGeral cg = new ClasseGeral();

        jtfBuscaMatricula.setText(jtfBuscaMatricula.getText().toUpperCase());

        if (cg.StringToLong(jtfBuscaMatricula.getText()) == 9999999) {
            JOptionPane.showMessageDialog(null, "Este número não é valido!", "Erro", JOptionPane.ERROR_MESSAGE, null);
            jtfBuscaMatricula.setText("");
        }
    }//GEN-LAST:event_jtfBuscaMatriculaFocusLost

    private void jtfBuscaFiliacaoPaiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfBuscaFiliacaoPaiFocusLost
        jtfBuscaFiliacaoPai.setText(jtfBuscaFiliacaoPai.getText().toUpperCase());
    }//GEN-LAST:event_jtfBuscaFiliacaoPaiFocusLost

    private void jtfBuscaFiliacaoMaeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfBuscaFiliacaoMaeFocusLost
        jtfBuscaFiliacaoMae.setText(jtfBuscaFiliacaoMae.getText().toUpperCase());
    }//GEN-LAST:event_jtfBuscaFiliacaoMaeFocusLost

    private void jrbModalidadeTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbModalidadeTodasActionPerformed
        modalidade = "";
    }//GEN-LAST:event_jrbModalidadeTodasActionPerformed

    private void jrbModalidadeBercarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbModalidadeBercarioActionPerformed
        modalidade = "BERÇÁRIO";
    }//GEN-LAST:event_jrbModalidadeBercarioActionPerformed

    private void jrbModalidadeMaternal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbModalidadeMaternal1ActionPerformed
        modalidade = "MATERNAL I";
    }//GEN-LAST:event_jrbModalidadeMaternal1ActionPerformed

    private void jrbModalidadeMaternal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbModalidadeMaternal2ActionPerformed
        modalidade = "MATERNAL II";
    }//GEN-LAST:event_jrbModalidadeMaternal2ActionPerformed

    private void jrbModalidadePre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbModalidadePre1ActionPerformed
        modalidade = "PRÉ I";
    }//GEN-LAST:event_jrbModalidadePre1ActionPerformed

    private void jrbModalidadePre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbModalidadePre2ActionPerformed
        modalidade = "PRÉ II";
    }//GEN-LAST:event_jrbModalidadePre2ActionPerformed

    private void jrbDesistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbDesistenciaActionPerformed
        
        if (jrbDesistencia.isSelected()) {
            tipoCadastro = "DESISTENCIA";
        }
        
    }//GEN-LAST:event_jrbDesistenciaActionPerformed

    private void jrbEgressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbEgressoActionPerformed
        
        if (jrbEgresso.isSelected()) {
            tipoCadastro = "EGRESSO";
        }
        
    }//GEN-LAST:event_jrbEgressoActionPerformed

    private void jrbTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbTransferenciaActionPerformed
        
        if (jrbTransferencia.isSelected()) {
            tipoCadastro = "TRANSFERENCIA";
        }
        
    }//GEN-LAST:event_jrbTransferenciaActionPerformed
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
    public void run() {
    jdBuscaAgendamento dialog = new jdBuscaAgendamento(new javax.swing.JFrame(), true);
    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
    public void windowClosing(java.awt.event.WindowEvent e) {
    System.exit(0);
    }
    });
    dialog.setVisible(true);
    }
    });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgModalidade;
    private javax.swing.ButtonGroup btgTipoCadastro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbBuscaCancelar;
    private javax.swing.JButton jbBuscaEnviarDados;
    private javax.swing.JButton jbBuscaFechar;
    private javax.swing.JButton jbBuscaPesquisar;
    private javax.swing.JComboBox jcbBuscaNomeEntidade;
    private javax.swing.JFormattedTextField jftfBuscaCpfMae;
    private javax.swing.JFormattedTextField jftfBuscaCpfPai;
    private javax.swing.JLabel jlbTotalAlunos;
    private javax.swing.JLabel jlbTotalBuscadoTabela;
    private javax.swing.JPanel jpBotoes;
    private javax.swing.JPanel jpBuscaAluno;
    private javax.swing.JRadioButton jrbAmbos;
    private javax.swing.JRadioButton jrbDesistencia;
    private javax.swing.JRadioButton jrbEgresso;
    private javax.swing.JRadioButton jrbFilaEspera;
    private javax.swing.JRadioButton jrbMatriculado;
    private javax.swing.JRadioButton jrbModalidadeBercario;
    private javax.swing.JRadioButton jrbModalidadeMaternal1;
    private javax.swing.JRadioButton jrbModalidadeMaternal2;
    private javax.swing.JRadioButton jrbModalidadePre1;
    private javax.swing.JRadioButton jrbModalidadePre2;
    private javax.swing.JRadioButton jrbModalidadeTodas;
    private javax.swing.JRadioButton jrbTransferencia;
    private javax.swing.JTable jtbBuscaAluno;
    private javax.swing.JTextField jtfBuscaFiliacaoMae;
    private javax.swing.JTextField jtfBuscaFiliacaoPai;
    private javax.swing.JTextField jtfBuscaMatricula;
    private javax.swing.JTextField jtfBuscaNomeAluno;
    // End of variables declaration//GEN-END:variables

//Outros Metodos ===========================================================================================================================================
    public void fechar() {

        cancelar();
        this.dispose();

    }

    public void cancelar() {

        DefaultTableModel modelo = (DefaultTableModel) jtbBuscaAluno.getModel();

        jtfBuscaNomeAluno.setText("");
        jtfBuscaFiliacaoMae.setText("");
        jtfBuscaFiliacaoPai.setText("");
        jtfBuscaMatricula.setText("");
        if (!tipoCadastroUsuario.equals("GERAL")) {
            jcbBuscaNomeEntidade.setSelectedItem(tipoCadastroUsuario);
        } else {
            jcbBuscaNomeEntidade.setSelectedIndex(0);
        }
        jftfBuscaCpfMae.setText("");
        jftfBuscaCpfPai.setText("");
        jrbModalidadeTodas.setSelected(true);
        jrbAmbos.setSelected(true);

        tipoCadastro = "";
        modalidade = "";
        imprimirTodos = false;

        modelo.setRowCount(0);
        setNumeroAlunosBuscadosNaTabela("0");
        jlbTotalAlunos.setText("0");
        
    }

    public void pesquisar() {

        DefaultTableModel modelo = (DefaultTableModel) jtbBuscaAluno.getModel();
        final TableRowSorter<TableModel> tabelaSorter = new TableRowSorter<TableModel>(modelo);
        jtbBuscaAluno.setRowSorter(tabelaSorter);
        
        iniciaDao();
        //DAO dao = new DAO();
        Aluno alun;
        List listaAluno = new ArrayList();
        String nomeAlun;
        String cpfPai;
        String cpfMae;
        String filiacaoPai;
        String filiacaoMae;
        String matric;
        String nomeEntid;

        if (jrbFilaEspera.isSelected()) {

            if (!tipoCadastroUsuario.equals("GERAL")) {

                if (imprimirTodos) {
                    nomeEntid = "";
                } else {
                    nomeEntid = jcbBuscaNomeEntidade.getSelectedItem().toString();
                }
                
            } else {
                nomeEntid = jcbBuscaNomeEntidade.getSelectedItem().toString();
            }

        } else {

            if (jcbBuscaNomeEntidade.getSelectedIndex() == 0) {
                nomeEntid = "";
            } else {
                nomeEntid = (String) jcbBuscaNomeEntidade.getSelectedItem();
            }

        }

        if (jtfBuscaNomeAluno.getText().isEmpty()) {
            nomeAlun = "";
        } else {
            nomeAlun = jtfBuscaNomeAluno.getText();
        }

        if (jftfBuscaCpfMae.getText().equals("   .   .   -  ")) {
            cpfMae = "";
        } else {
            cpfMae = jftfBuscaCpfMae.getText();
        }

        if (jftfBuscaCpfPai.getText().equals("   .   .   -  ")) {
            cpfPai = "";
        } else {
            cpfPai = jftfBuscaCpfPai.getText();
        }

        if (jtfBuscaFiliacaoMae.getText().isEmpty()) {
            filiacaoMae = "";
        } else {
            filiacaoMae = jtfBuscaFiliacaoMae.getText();
        }

        if (jtfBuscaFiliacaoPai.getText().isEmpty()) {
            filiacaoPai = "";
        } else {
            filiacaoPai = jtfBuscaFiliacaoPai.getText();
        }

        if (jtfBuscaMatricula.getText().isEmpty()) {
            matric = "";
        } else {
            matric = jtfBuscaMatricula.getText();
        }

        listaAluno = (List) dao.listarAlunosCadastrados(nomeAlun, cpfPai, cpfMae, filiacaoPai, filiacaoMae, matric, nomeEntid, tipoCadastro, modalidade);

        modelo.setRowCount(0);
        iniciaEditaOrdemTabela();

        for (int i = 0; i < listaAluno.size(); i++) {

            String filiacaoPaiMae;
            String cpfPaiMae;

            alun = (Aluno) listaAluno.get(i);

            if (!alun.getFiliacaoPai().isEmpty()) {
                filiacaoPaiMae = alun.getFiliacaoPai();
            } else {
                filiacaoPaiMae = alun.getFiliacaoMae();
            }

            if (!alun.getCpfPai().equals("   .   .   -  ")) {
                cpfPaiMae = alun.getCpfPai();
            } else {
                cpfPaiMae = alun.getCpfMae();
            }

            modelo.addRow(new String[]{editaOrdemTabela.editaOrdem(i + 1), String.valueOf(alun.getNomeAluno()), String.valueOf(filiacaoPaiMae), String.valueOf(cpfPaiMae), String.valueOf(alun.getNomeEntidade()), String.valueOf(alun.getDataNascimento()), String.valueOf(alun.getDataCadastro()), String.valueOf(alun.getModalidade()), String.valueOf(alun.getTipoCadastro()), String.valueOf(alun.getMatricula()), String.valueOf(alun.getCodigoAluno())});

        }

        setNumeroAlunosBuscadosNaTabela(String.valueOf(modelo.getRowCount()));
        setNumeroAlunos();

        if (jtbBuscaAluno.getRowCount() > 0) {
            jtbBuscaAluno.getSelectionModel().setSelectionInterval(0, 0);
        } else {
            iniciaClasseGeral();
            
            classeGeral.msgInforma("Não há alunos com estes dados!");
        }

    }

    public void buscaDados() {

        iniciaDao();
        iniciaAluno();
        //DAO dao = new DAO();

        String nomeAlun;
        String codigoAlun;

        nomeAlun = (String) jtbBuscaAluno.getValueAt(jtbBuscaAluno.getSelectedRow(), 1);
        codigoAlun = (String) jtbBuscaAluno.getValueAt(jtbBuscaAluno.getSelectedRow(), 10);

        //aluno = (Aluno) dao.buscaAluno(nomeAlun, codigoAlun);
        aluno = (Aluno) dao.busca(aluno, Integer.parseInt(codigoAlun));

    }

    public void preencheComboCmeis() {

        iniciaDao();
        //DAO dao = new DAO();
        List listaCmeis = new ArrayList();

        jcbBuscaNomeEntidade.removeAllItems();
        jcbBuscaNomeEntidade.addItem("");

        listaCmeis = dao.listarCmeis();

        for (int i = 0; i < listaCmeis.size(); i++) {
            jcbBuscaNomeEntidade.addItem(listaCmeis.get(i));
        }

        if (!tipoCadastroUsuario.equals("GERAL")) {
            jcbBuscaNomeEntidade.setSelectedItem(tipoCadastroUsuario);
            //jcbBuscaNomeEntidade.setEnabled(false);
        }

    }

//Geradores, Validadores===========================================================================================================================================
    public void iniciaAluno() {
        
        if (aluno == null) {
            aluno = new Aluno();
        }
        
    }
    
    public void iniciaClasseGeral() {
        
        if (classeGeral == null) {
            classeGeral = new ClasseGeral();
        }
        
    }
    
    public void iniciaDao() {

        if (dao == null) {
            dao = new DAO();
        }

    }
    
    public void iniciaEditaOrdemTabela() {
        
        if (editaOrdemTabela == null) {
            editaOrdemTabela = new EditaOrdemTabela();
        }
        
    }
//Getters and Setters===========================================================================================================================================
    public void setNumeroCaracteres() {

        jtfBuscaNomeAluno.setDocument(new FixedLengthDocument(60));

    }

    public String getTipoCadastroUsuario() {
        return tipoCadastroUsuario;
    }

    public void setTipoCadastroUsuario(String tipoCadastroUsuario) {
        this.tipoCadastroUsuario = tipoCadastroUsuario;
        preencheComboCmeis();
    }

    public Aluno getAluno() {

        return aluno;

    }

    public void setAluno() {
        aluno = null;
    }

    public void setNumeroAlunos() {

        iniciaDao();
        //DAO dao = new DAO();

        jlbTotalAlunos.setText("" + dao.getNumeroAlunos());

    }

    public void setNumeroAlunosBuscadosNaTabela(String numeroAlunosBuscadosNaTabela) {

        jlbTotalBuscadoTabela.setText(numeroAlunosBuscadosNaTabela);

    }

//Metodos DAO===========================================================================================================================================
    
}
