/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jfCadastroEscola.java
 *
 * Created on 27/01/2010, 09:03:18
 */
package visual;

import conexao.Conexao;
import controlador.ClasseGeral;
import controlador.ControleCaracteresEspeciais;
import controlador.ControleImagem;
import controlador.ControleVersao;
import controlador.FixedLengthDocument;
import controlador.Formatos;
import dao.DAO;
import excecoes.ExcCadastro;
import java.awt.Image;
import java.awt.Toolkit;
import java.text.ParseException;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.Cmei;
import modelo.Permissoes;
import modelo.Usuario;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author luiz
 */
public class jfCadastroCmei extends javax.swing.JFrame {

    private static ControleVersao versao = new ControleVersao();
    private DAO dao;
    private Cmei cmei;
    private Formatos formatos = new Formatos();
    private ClasseGeral classeGeral;
    private ControleCaracteresEspeciais controleCaracteresEspeciais;
    private ControleImagem controleImagem = new ControleImagem();

    private jdBuscaCmei jdbc;
    private JasperPrint jPrint;
    private JasperViewer jViewer;

    private int codigo = 0;
    private int capacidadeAlunos;
    private int capacidadeVagasDisponiveis;
    private String opcao = "salvar";
    private String nomeUsuario;
    private String cmeiVerificado;
    private boolean cadastrarCmei;

    /** Creates new form jfCadastroEscola */
    public jfCadastroCmei() {
        super("Cadastro CMEI - " + versao.getVersao() + " - " + versao.getAno());
        initComponents();

        //Altera icone na barra de titulo
        Toolkit kit = Toolkit.getDefaultToolkit();
        Image img = kit.getImage(controleImagem.getIconeImagem());
        this.setIconImage(img);

        //maximiza tela
        //this.setExtendedState(MAXIMIZED_BOTH);

        //centraliza tela
        setSize(getWidth(), getHeight());
        setLocationRelativeTo(null);

        try {
            jftfTelefone.setFormatterFactory(formatos.getFormatoTelefone());
        } catch (ParseException ex) {
            iniciaClasseGeral();
            Logger.getLogger(jfCadastroCmei.class.getName()).log(Level.SEVERE, null, ex);
            classeGeral.msgErro("Não foi possivel formatar campo de telefone, \n Contate o Administrador!");
        }

        setNumeroCaracteres();

        jtfMunicipio.setText("CASCAVEL");

        jtfVagasDisponiveis.setEditable(false);
        jtfTotalLotacoes.setEditable(false);
        jtfNumeroEstagiarios.setEditable(false);
        jtfNumeroServidores.setEditable(false);

        jtfBercario.setText("0");
        jtfMaternal.setText("0");
        jtfPre.setText("0");
        
        desabilitaBotoes();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpCadastroCmei = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfNomeCmei = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtfEndereco = new javax.swing.JTextField();
        jtfNumero = new javax.swing.JTextField();
        jtfMunicipio = new javax.swing.JTextField();
        jftfTelefone = new javax.swing.JFormattedTextField();
        jtfBairro = new javax.swing.JTextField();
        jtfCoordenadorAtual = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtfCapacidadeAlunos = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtfVagasDisponiveis = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jtfBercario = new javax.swing.JTextField();
        jtfMaternal = new javax.swing.JTextField();
        jtfPre = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jtfTotalLotacoes = new javax.swing.JTextField();
        jtfNumeroServidores = new javax.swing.JTextField();
        jtfNumeroEstagiarios = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jpBotoes = new javax.swing.JPanel();
        jbNovo = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbAlterar = new javax.swing.JButton();
        jbImprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jpCadastroCmei.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Nome do CMEI: ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Endereço: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Município: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Bairro: ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Coordenador Atual: ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Telefone: ");

        jtfNomeCmei.setBackground(new java.awt.Color(204, 204, 255));
        jtfNomeCmei.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfNomeCmei.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jtfNomeCmei.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfNomeCmeiFocusLost(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Número: ");

        jtfEndereco.setBackground(new java.awt.Color(204, 204, 255));
        jtfEndereco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfEndereco.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jtfEndereco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfEnderecoFocusLost(evt);
            }
        });

        jtfNumero.setBackground(new java.awt.Color(204, 204, 255));
        jtfNumero.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfNumero.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jtfNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfNumeroFocusLost(evt);
            }
        });

        jtfMunicipio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfMunicipio.setText("CASCAVEL");
        jtfMunicipio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jtfMunicipio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfMunicipioFocusLost(evt);
            }
        });

        jftfTelefone.setBackground(new java.awt.Color(204, 204, 255));
        jftfTelefone.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jftfTelefone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jtfBairro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfBairro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jtfBairro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfBairroFocusLost(evt);
            }
        });

        jtfCoordenadorAtual.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfCoordenadorAtual.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jtfCoordenadorAtual.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfCoordenadorAtualFocusLost(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Capacidade de Alunos: ");

        jtfCapacidadeAlunos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfCapacidadeAlunos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jtfCapacidadeAlunos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfCapacidadeAlunosFocusLost(evt);
            }
        });

        jLabel10.setText("Vagas Disponiveis: ");

        jtfVagasDisponiveis.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfVagasDisponiveis.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jtfVagasDisponiveis.setEnabled(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Número de Salas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Berçários: ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Maternal: ");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Pré: ");

        jtfBercario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfBercario.setText("0");
        jtfBercario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jtfBercario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfBercarioFocusLost(evt);
            }
        });

        jtfMaternal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfMaternal.setText("0");
        jtfMaternal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jtfMaternal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfMaternalFocusLost(evt);
            }
        });

        jtfPre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfPre.setText("0");
        jtfPre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jtfPre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfPreFocusLost(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel16.setText("(0 a 1 ano)");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel17.setText("(1 a 3 anos)");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel21.setText("(4 a 5 anos)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel11)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtfBercario, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtfMaternal, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtfPre, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel21)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtfBercario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtfMaternal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jtfPre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lotações", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("Número de Lotações: ");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("Número de Servidores: ");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("Número de Estagiários: ");

        jtfTotalLotacoes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfTotalLotacoes.setText("0");
        jtfTotalLotacoes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jtfTotalLotacoes.setEnabled(false);

        jtfNumeroServidores.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfNumeroServidores.setText("0");
        jtfNumeroServidores.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jtfNumeroServidores.setEnabled(false);

        jtfNumeroEstagiarios.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfNumeroEstagiarios.setText("0");
        jtfNumeroEstagiarios.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jtfNumeroEstagiarios.setEnabled(false);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel25.setText("(Concursados)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfTotalLotacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jtfNumeroServidores, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel25))
                    .addComponent(jtfNumeroEstagiarios, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jtfTotalLotacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jtfNumeroServidores, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jtfNumeroEstagiarios, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpCadastroCmeiLayout = new javax.swing.GroupLayout(jpCadastroCmei);
        jpCadastroCmei.setLayout(jpCadastroCmeiLayout);
        jpCadastroCmeiLayout.setHorizontalGroup(
            jpCadastroCmeiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadastroCmeiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCadastroCmeiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCadastroCmeiLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jpCadastroCmeiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpCadastroCmeiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpCadastroCmeiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtfNomeCmei)
                                .addGroup(jpCadastroCmeiLayout.createSequentialGroup()
                                    .addComponent(jtfEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jpCadastroCmeiLayout.createSequentialGroup()
                                    .addGroup(jpCadastroCmeiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jtfCoordenadorAtual, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtfBairro, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtfMunicipio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jftfTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)))
                            .addGroup(jpCadastroCmeiLayout.createSequentialGroup()
                                .addComponent(jtfCapacidadeAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfVagasDisponiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jpCadastroCmeiLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        jpCadastroCmeiLayout.setVerticalGroup(
            jpCadastroCmeiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadastroCmeiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCadastroCmeiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfNomeCmei, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCadastroCmeiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCadastroCmeiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jftfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCadastroCmeiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCadastroCmeiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfCoordenadorAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCadastroCmeiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtfCapacidadeAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jtfVagasDisponiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpCadastroCmeiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpBotoes.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());

        jbNovo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete02.png"))); // NOI18N
        jbNovo.setText("Novo");
        jbNovo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbNovo.setEnabled(false);
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jbSalvar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/OK.png"))); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbBuscar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jbBuscar.setText("Buscar");
        jbBuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jbCancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbExcluir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete02.png"))); // NOI18N
        jbExcluir.setText("Excluir");
        jbExcluir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbExcluir.setEnabled(false);
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbAlterar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/reload.png"))); // NOI18N
        jbAlterar.setText("Alterar");
        jbAlterar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbAlterar.setEnabled(false);
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jbImprimir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imprimir.png"))); // NOI18N
        jbImprimir.setText("Imprimir");
        jbImprimir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbImprimir.setEnabled(false);
        jbImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpBotoesLayout = new javax.swing.GroupLayout(jpBotoes);
        jpBotoes.setLayout(jpBotoesLayout);
        jpBotoesLayout.setHorizontalGroup(
            jpBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBotoesLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jbNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpBotoesLayout.setVerticalGroup(
            jpBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpCadastroCmei, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpCadastroCmei, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        cancelar();
}//GEN-LAST:event_jbNovoActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        
        verificaCadastroCmei();

        if (opcao.equals("salvar")) {

            if (!cmeiVerificado.isEmpty()) {
                iniciaClasseGeral();
                classeGeral.msgAtencao("Esse CMEI já existe!");
            } else {
                salvar();
                opcao = "salvar";
            }

        } else if (opcao.equals("alterar")) {

            atualizar();
            opcao = "salvar";

        }
        
}//GEN-LAST:event_jbSalvarActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed

        if (jdbc == null) {
            jdbc = new jdBuscaCmei(null, true);
        }

        jdbc.setVisible(true);

        setCmeiBuscado(jdbc.getCmei());
        jdbc.setCmei();

    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        cancelar();
}//GEN-LAST:event_jbCancelarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        excluir();
}//GEN-LAST:event_jbExcluirActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed

        abilitaCampos();

        jbAlterar.setEnabled(false);

        opcao = "alterar";

        jbSalvar.setEnabled(true);

}//GEN-LAST:event_jbAlterarActionPerformed

    private void jtfMunicipioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfMunicipioFocusLost
        if (!jtfMunicipio.getText().isEmpty()) {
            jtfMunicipio.setText(jtfMunicipio.getText().toUpperCase());
        }
    }//GEN-LAST:event_jtfMunicipioFocusLost

    private void jtfBairroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfBairroFocusLost
        if (jtfBairro.getText().isEmpty()) {
            jtfBairro.setText(jtfBairro.getText().toUpperCase());
        }
    }//GEN-LAST:event_jtfBairroFocusLost

    private void jtfNumeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfNumeroFocusLost
        if (jtfNumero.getText().isEmpty()) {
            jtfNumero.setText(jtfNumero.getText().toUpperCase());
        }
    }//GEN-LAST:event_jtfNumeroFocusLost

    private void jtfCapacidadeAlunosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCapacidadeAlunosFocusLost
        
        if (!jtfCapacidadeAlunos.getText().isEmpty()) {
            ClasseGeral cg = new ClasseGeral();

            jtfCapacidadeAlunos.setText(cg.somenteNumero(jtfCapacidadeAlunos.getText()));

            if (opcao.equals("alterar")) {

                if (capacidadeAlunos < Integer.valueOf(jtfCapacidadeAlunos.getText())) {

                    jtfVagasDisponiveis.setText("" + ((Integer.valueOf(jtfCapacidadeAlunos.getText()) - capacidadeAlunos) + capacidadeVagasDisponiveis));

                } else {

                    jtfVagasDisponiveis.setText("" + (capacidadeVagasDisponiveis - (capacidadeAlunos - Integer.valueOf(jtfCapacidadeAlunos.getText()))));

                }

            } else {
                jtfVagasDisponiveis.setText(jtfCapacidadeAlunos.getText());
            }
        }
        
    }//GEN-LAST:event_jtfCapacidadeAlunosFocusLost

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        fechar();
    }//GEN-LAST:event_formWindowClosing

    private void jbImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbImprimirActionPerformed

        //ADOGeral ag = new ADOGeral();
        Conexao conexao = new Conexao();
        HashMap parametros = new HashMap();
        try {
            //System.out.println(codigoRegistro);
            //parametros.put("titulo", "Titulo Relatorio");
            parametros.put("codigoCmei", new Integer(codigo));
            //parametros.put("codigo", lista.get(0).getNome();
            //ADOGeral.conectar();
            conexao.getConexao();
        } catch (ExcCadastro ex) {
            Logger.getLogger(jfCadastroCmei.class.getName()).log(Level.SEVERE, null, ex);
        }

        //        JRDataSource jrds = new JRBeanCollectionDataSource(lista);

        try {

            //jReport = JasperCompileManager.compileReport("E:/LUIZ/PROJETOS JAVA/CORPORATIVO/m2GestaoClinicas/FichaPaciente.jrxml");
            //jPrint = JasperFillManager.fillReport("C:/m2GestaoClinicas/FichaPaciente.jasper", parametros, ADOGeral.getConexao());
            jPrint = JasperFillManager.fillReport("Cmei.jasper", parametros, conexao.getConexao());
            //jPrint = JasperFillManager.fillReport(jReport, parametros, jrds);

            //if (!(jViewer == null)) {
            //jViewer = new JasperViewer(jPrint, false);
            //jViewer.setExtendedState(MAXIMIZED_BOTH);
            if (jPrint != null) {
                jViewer.viewReport(jPrint, false);
                jPrint = null;
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_jbImprimirActionPerformed

    private void jtfBercarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfBercarioFocusLost
        
        if (!jtfBercario.getText().isEmpty()) {
            ClasseGeral cg = new ClasseGeral();

            jtfBercario.setText(cg.somenteNumero(jtfBercario.getText()));
        }
        
    }//GEN-LAST:event_jtfBercarioFocusLost

    private void jtfMaternalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfMaternalFocusLost
        
        if (!jtfMaternal.getText().isEmpty()) {
            ClasseGeral cg = new ClasseGeral();

            jtfMaternal.setText(cg.somenteNumero(jtfMaternal.getText()));
        }
        
    }//GEN-LAST:event_jtfMaternalFocusLost

    private void jtfPreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfPreFocusLost
        
        if (!jtfPre.getText().isEmpty()) {
            ClasseGeral cg = new ClasseGeral();

            jtfPre.setText(cg.somenteNumero(jtfPre.getText()));
        }
        
    }//GEN-LAST:event_jtfPreFocusLost

    private void jtfNomeCmeiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfNomeCmeiFocusLost
        if (!jtfNomeCmei.getText().isEmpty()) {
            jtfNomeCmei.setText(jtfNomeCmei.getText().toUpperCase());
        }
    }//GEN-LAST:event_jtfNomeCmeiFocusLost

    private void jtfEnderecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfEnderecoFocusLost
        if (!jtfEndereco.getText().isEmpty()) {
            jtfEndereco.setText(jtfEndereco.getText().toUpperCase());
        }
    }//GEN-LAST:event_jtfEnderecoFocusLost

    private void jtfCoordenadorAtualFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCoordenadorAtualFocusLost
        if (!jtfCoordenadorAtual.getText().isEmpty()) {
            jtfCoordenadorAtual.setText(jtfCoordenadorAtual.getText().toUpperCase());
        }
    }//GEN-LAST:event_jtfCoordenadorAtualFocusLost
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
    public void run() {
    new jfCadastroEscola().setVisible(true);
    }
    });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbImprimir;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JFormattedTextField jftfTelefone;
    private javax.swing.JPanel jpBotoes;
    private javax.swing.JPanel jpCadastroCmei;
    private javax.swing.JTextField jtfBairro;
    private javax.swing.JTextField jtfBercario;
    private javax.swing.JTextField jtfCapacidadeAlunos;
    private javax.swing.JTextField jtfCoordenadorAtual;
    private javax.swing.JTextField jtfEndereco;
    private javax.swing.JTextField jtfMaternal;
    private javax.swing.JTextField jtfMunicipio;
    private javax.swing.JTextField jtfNomeCmei;
    private javax.swing.JTextField jtfNumero;
    private javax.swing.JTextField jtfNumeroEstagiarios;
    private javax.swing.JTextField jtfNumeroServidores;
    private javax.swing.JTextField jtfPre;
    private javax.swing.JTextField jtfTotalLotacoes;
    private javax.swing.JTextField jtfVagasDisponiveis;
    // End of variables declaration//GEN-END:variables

//Outros Metodos===================================================================================================================================
    public void fechar() {

        if (!jtfNomeCmei.getText().isEmpty() || !jtfEndereco.getText().isEmpty() || !jtfNumero.getText().isEmpty() || !jftfTelefone.getText().equals("(  )    -    ")) {

            iniciaClasseGeral();
            classeGeral.msgAtencao("Cancele ou Salve o Cadastro em Edição!");

        } else {
            dao = null;
            this.dispose();
        }

    }

    public void cancelar() {

        jtfNomeCmei.setText("");
        jtfEndereco.setText("");
        jtfNumero.setText("");
        jtfMunicipio.setText("CASCAVEL");
        jtfBairro.setText("");
        jftfTelefone.setText("");
        jtfBairro.setText("");
        jtfCoordenadorAtual.setText("");
        jtfCapacidadeAlunos.setText("");
        jtfVagasDisponiveis.setText("");
        jtfBercario.setText("0");
        jtfMaternal.setText("0");
        jtfPre.setText("0");
        jtfTotalLotacoes.setText("0");
        jtfNumeroServidores.setText("0");
        jtfNumeroEstagiarios.setText("0");

        abilitaCampos();

        desabilitaBotoes();

        jtfEndereco.transferFocusBackward();

        opcao = "salvar";
        
        cmei = null;

    }

    public void abilitaCampos() {

        jtfNomeCmei.setEditable(true);
        jtfEndereco.setEditable(true);
        jtfNumero.setEditable(true);
        jtfMunicipio.setEditable(true);
        jtfBairro.setEditable(true);
        jftfTelefone.setEditable(true);
        jtfBairro.setEditable(true);
        jtfCoordenadorAtual.setEditable(true);
        jtfCapacidadeAlunos.setEditable(true);
        jtfCapacidadeAlunos.setEnabled(true);
        jtfBercario.setEditable(true);
        jtfMaternal.setEditable(true);
        jtfPre.setEditable(true);
        jtfVagasDisponiveis.setEditable(false);

    }

    public void desabilitaCampos() {

        jtfNomeCmei.setEditable(false);
        jtfEndereco.setEditable(false);
        jtfNumero.setEditable(false);
        jtfMunicipio.setEditable(false);
        jtfBairro.setEditable(false);
        jftfTelefone.setEditable(false);
        jtfBairro.setEditable(false);
        jtfCoordenadorAtual.setEditable(false);
        jtfCapacidadeAlunos.setEditable(false);
        jtfCapacidadeAlunos.setEnabled(false);
        jtfBercario.setEditable(false);
        jtfMaternal.setEditable(false);
        jtfPre.setEditable(false);
        jtfVagasDisponiveis.setEditable(false);

    }

    public void abilitaBotoes() {

        jbNovo.setEnabled(true);
        jbCancelar.setEnabled(true);
        jbBuscar.setEnabled(true);
        jbImprimir.setEnabled(true);

        if (cadastrarCmei == true) {
            jbSalvar.setEnabled(false);
            jbExcluir.setEnabled(true);
            jbAlterar.setEnabled(true);
        } else if (verificaMatriculaAbilitacao()) {
            jbSalvar.setEnabled(false);
            jbExcluir.setEnabled(true);
            jbAlterar.setEnabled(true);
        } else {
            jbSalvar.setEnabled(false);
            jbExcluir.setEnabled(false);
            jbAlterar.setEnabled(false);
        }

    }

    public void desabilitaBotoes() {

        jbNovo.setEnabled(false);
        jbCancelar.setEnabled(true);
        jbBuscar.setEnabled(true);
        jbImprimir.setEnabled(false);

        if (cadastrarCmei == true) {
            jbSalvar.setEnabled(true);
            jbExcluir.setEnabled(false);
            jbAlterar.setEnabled(false);
        } else {
            jbSalvar.setEnabled(false);
            jbExcluir.setEnabled(false);
            jbAlterar.setEnabled(false);
        }

    }

//Geradores, Validadores===================================================================================================================================
    public void iniciaClasseGeral() {
        
        if (classeGeral == null) {
            classeGeral = new ClasseGeral();
        }
        
    }
    
    public void iniciaCmei() {
        
        if (cmei == null) {
            cmei = new Cmei();
        }
        
    }
    
    public void iniciaDao() {

        if (dao == null) {
            dao = new DAO();
        }

    }
    
    public void iniciaControleCaracteresEspeciais() {
        
        if (controleCaracteresEspeciais == null) {
            controleCaracteresEspeciais = new ControleCaracteresEspeciais();
        }
        
    }
    
    public void verificaCadastroCmei() {

        iniciaDao();
        //DAO dao = new DAO();

        cmeiVerificado = dao.verificarCadastroCmei(jtfNomeCmei.getText());

    }

    public boolean verificaMatriculaAbilitacao() {

        iniciaDao();
        //DAO dao = new DAO();
        Usuario user;
        String matric;

        user = (Usuario) dao.buscaUsuario(nomeUsuario, "");

        if (Integer.valueOf(user.getMatricula()) == cmei.getCodigoCmei()) {
            return true;
        } else {
            return false;
        }

    }

    public String getDataHoje() {

        GregorianCalendar calendar = new GregorianCalendar();
        Date data = calendar.getTime();

        String mes = "";
        String dia = "";
        int diaAux = data.getDate();
        String ano = (data.getYear() + 1900 + "");
        int mesAux = data.getMonth() + 1;

        if (diaAux < 10) {
            dia = "0" + diaAux;
        } else {
            dia = "" + diaAux;
        }

        if (mesAux < 10) {
            mes = "0" + mesAux;
        } else {
            mes = "" + mesAux;
        }

        return dia + mes + ano;

    }

//Getters and Setters===================================================================================================================================
    public void setCmeiBuscado(Cmei cmeiBuscado) {

        if (cmeiBuscado.getNomeEntidade().isEmpty()) {
        } else {

            iniciaDao();
            iniciaCmei();
            iniciaControleCaracteresEspeciais();
            
            jtfNomeCmei.setText(controleCaracteresEspeciais.getCaracterEspecial(cmeiBuscado.getNomeEntidade()));
            jtfEndereco.setText(controleCaracteresEspeciais.getCaracterEspecial(cmeiBuscado.getEndereco()));
            jtfNumero.setText(cmeiBuscado.getNumeroEndereco());
            jtfMunicipio.setText(controleCaracteresEspeciais.getCaracterEspecial(cmeiBuscado.getMunicipio()));
            jftfTelefone.setText(cmeiBuscado.getTelefone());
            jtfBairro.setText(controleCaracteresEspeciais.getCaracterEspecial(cmeiBuscado.getBairro()));
            jtfCoordenadorAtual.setText(controleCaracteresEspeciais.getCaracterEspecial(cmeiBuscado.getCoordenadorAtual()));
            jtfCapacidadeAlunos.setText(cmeiBuscado.getCapacidadeAlunos());
            
            jtfBercario.setText("" + cmeiBuscado.getNumeroSalasBercarios());
            jtfMaternal.setText("" + cmeiBuscado.getNumeroSalasMaternal());
            jtfPre.setText("" + cmeiBuscado.getNumeroSalasPre());
            jtfTotalLotacoes.setText("" + cmeiBuscado.getNumeroLotacoes());
            jtfNumeroServidores.setText("" + cmeiBuscado.getServidoresConcursados());
            jtfNumeroEstagiarios.setText("" + cmeiBuscado.getNumeroEstagiarios());

            capacidadeAlunos = Integer.valueOf(cmeiBuscado.getCapacidadeAlunos());
            capacidadeVagasDisponiveis = capacidadeAlunos - dao.getNumeroAlunosMatriculados(cmeiBuscado.getNomeEntidade());

            codigo = cmeiBuscado.getCodigoCmei();
            cmei.setCodigoCmei(codigo);

            jtfVagasDisponiveis.setText(capacidadeVagasDisponiveis + "");
            
            desabilitaCampos();

            abilitaBotoes();

        }

    }

    public void setNumeroCaracteres() {

        jtfNomeCmei.setDocument(new FixedLengthDocument(60));
        jtfEndereco.setDocument(new FixedLengthDocument(60));
        jtfNumero.setDocument(new FixedLengthDocument(10));
        jtfMunicipio.setDocument(new FixedLengthDocument(60));
        jtfBairro.setDocument(new FixedLengthDocument(60));
        jtfCoordenadorAtual.setDocument(new FixedLengthDocument(60));
        jtfCapacidadeAlunos.setDocument(new FixedLengthDocument(6));
        jtfBercario.setDocument(new FixedLengthDocument(6));
        jtfMaternal.setDocument(new FixedLengthDocument(6));
        jtfPre.setDocument(new FixedLengthDocument(6));

    }

    public String getNomeUsuario() {
        return nomeUsuario;
    }

    public void setNomeUsuario(String nomeUsuario) {
        this.nomeUsuario = nomeUsuario;
        getPermissoes();
        desabilitaBotoes();
    }

    public void getPermissoes() {
        Permissoes permissoes;
        iniciaDao();
        //DAO dao = new DAO();

        permissoes = (Permissoes) dao.buscaPermissoes(getNomeUsuario());

        cadastrarCmei = permissoes.isCadastrarCmei();
    }

//Metodos DAO===================================================================================================================================
    public void salvar() {

        if (!jtfNomeCmei.getText().isEmpty() || !jtfEndereco.getText().isEmpty() || !jtfNumero.getText().isEmpty() || !jftfTelefone.getText().equals("(  )    -    ")) {

            iniciaDao();
            iniciaCmei();
            iniciaControleCaracteresEspeciais();

            cmei.setBairro(controleCaracteresEspeciais.getCodigoCaracterEpecial(jtfBairro.getText()));
            cmei.setCapacidadeAlunos(jtfCapacidadeAlunos.getText());
            cmei.setVagasDisponiveis(Integer.valueOf(jtfVagasDisponiveis.getText()));
            cmei.setCoordenadorAtual(controleCaracteresEspeciais.getCodigoCaracterEpecial(jtfCoordenadorAtual.getText()));
            cmei.setEndereco(controleCaracteresEspeciais.getCodigoCaracterEpecial(jtfEndereco.getText()));
            cmei.setMunicipio(controleCaracteresEspeciais.getCodigoCaracterEpecial(jtfMunicipio.getText()));
            cmei.setNomeEntidade(controleCaracteresEspeciais.getCodigoCaracterEpecial(jtfNomeCmei.getText()));
            cmei.setNumeroEndereco(jtfNumero.getText());
            cmei.setTelefone(jftfTelefone.getText());
            cmei.setNumeroSalasBercarios(Integer.valueOf(jtfBercario.getText()));
            cmei.setNumeroSalasMaternal(Integer.valueOf(jtfMaternal.getText()));
            cmei.setNumeroSalasPre(Integer.valueOf(jtfPre.getText()));

            dao.inserir(cmei, 7);
            cancelar();

        } else {
            iniciaClasseGeral();
            classeGeral.msgAtencao("Complete os Campos Obrigatórios, destacados em Azul!");
        }

    }

    public void atualizar() {

        if (!jtfNomeCmei.getText().isEmpty() || !jtfEndereco.getText().isEmpty() || !jtfNumero.getText().isEmpty() || !jftfTelefone.getText().equals("")) {

            iniciaDao();
            iniciaCmei();
            iniciaControleCaracteresEspeciais();

            cmei.setBairro(controleCaracteresEspeciais.getCodigoCaracterEpecial(jtfBairro.getText()));
            cmei.setCapacidadeAlunos(jtfCapacidadeAlunos.getText());
            cmei.setVagasDisponiveis(Integer.valueOf(jtfVagasDisponiveis.getText()));
            cmei.setCoordenadorAtual(controleCaracteresEspeciais.getCodigoCaracterEpecial(jtfCoordenadorAtual.getText()));
            cmei.setEndereco(controleCaracteresEspeciais.getCodigoCaracterEpecial(jtfEndereco.getText()));
            cmei.setMunicipio(controleCaracteresEspeciais.getCodigoCaracterEpecial(jtfMunicipio.getText()));
            cmei.setNomeEntidade(controleCaracteresEspeciais.getCodigoCaracterEpecial(jtfNomeCmei.getText()));
            cmei.setNumeroEndereco(jtfNumero.getText());
            cmei.setTelefone(jftfTelefone.getText());
            cmei.setNumeroSalasBercarios(Integer.valueOf(jtfBercario.getText()));
            cmei.setNumeroSalasMaternal(Integer.valueOf(jtfMaternal.getText()));
            cmei.setNumeroSalasPre(Integer.valueOf(jtfPre.getText()));

            dao.atualizar(cmei, 7);
            cancelar();

        } else {
            iniciaClasseGeral();
            classeGeral.msgAtencao("Complete os Campos Obrigatórios, destacados em Azul!");
        }

    }

    public void excluir() {

        iniciaClasseGeral();

        if (classeGeral.msgConfirma("Deseja excluir esta entidade?")) {

            iniciaDao();
            iniciaCmei();
            dao.excluir(cmei, 7);
            cancelar();

        }

    }
}
