/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jfImpressosCmei.java
 *
 * Created on 16/08/2010, 06:38:24
 */

package visual;

import conexao.Conexao;
import controlador.ControleImagem;
import controlador.ControleVersao;
import dao.DAO;
import excecoes.ExcCadastro;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Permissoes;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author luizam
 */
public class jfImpressosRelatorio extends javax.swing.JFrame {

    private static ControleVersao versao = new ControleVersao();
    private ControleImagem controleImagem = new ControleImagem();
    private DAO dao;
    
    private JasperPrint jPrint;
    private JasperViewer jViewer;

    private String nomeUsuario;
    private boolean imprimirCmei;

    /** Creates new form jfImpressosCmei */
    public jfImpressosRelatorio() {
        super("Impressos Relatório - " + versao.getVersao() + " - " + versao.getAno());
        initComponents();

        //Altera icone na barra de titulo
        Toolkit kit = Toolkit.getDefaultToolkit();
        Image img = kit.getImage(controleImagem.getIconeImagem());
        this.setIconImage(img);

        //centraliza tela
        setSize(getWidth(), getHeight());
        setLocationRelativeTo(null);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgImpressosCmei = new javax.swing.ButtonGroup();
        jpImpressaoCmei = new javax.swing.JPanel();
        jrbTodosCmeis = new javax.swing.JRadioButton();
        jrbPorCmei = new javax.swing.JRadioButton();
        jcbNomeEntidade = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jpBotoes = new javax.swing.JPanel();
        jbImprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jpImpressaoCmei.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());

        btgImpressosCmei.add(jrbTodosCmeis);
        jrbTodosCmeis.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jrbTodosCmeis.setSelected(true);
        jrbTodosCmeis.setText("Todos os CMEI's");
        jrbTodosCmeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbTodosCmeisActionPerformed(evt);
            }
        });

        btgImpressosCmei.add(jrbPorCmei);
        jrbPorCmei.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jrbPorCmei.setText("Por CMEI");
        jrbPorCmei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbPorCmeiActionPerformed(evt);
            }
        });

        jcbNomeEntidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbNomeEntidade.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jcbNomeEntidade.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("(Total)");

        javax.swing.GroupLayout jpImpressaoCmeiLayout = new javax.swing.GroupLayout(jpImpressaoCmei);
        jpImpressaoCmei.setLayout(jpImpressaoCmeiLayout);
        jpImpressaoCmeiLayout.setHorizontalGroup(
            jpImpressaoCmeiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpImpressaoCmeiLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jpImpressaoCmeiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbPorCmei)
                    .addGroup(jpImpressaoCmeiLayout.createSequentialGroup()
                        .addComponent(jrbTodosCmeis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(jpImpressaoCmeiLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jcbNomeEntidade, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(317, Short.MAX_VALUE))
        );
        jpImpressaoCmeiLayout.setVerticalGroup(
            jpImpressaoCmeiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpImpressaoCmeiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpImpressaoCmeiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbTodosCmeis)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbPorCmei)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbNomeEntidade, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jpBotoes.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());

        jbImprimir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imprimir.png"))); // NOI18N
        jbImprimir.setText("Imprimir");
        jbImprimir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpBotoesLayout = new javax.swing.GroupLayout(jpBotoes);
        jpBotoes.setLayout(jpBotoesLayout);
        jpBotoesLayout.setHorizontalGroup(
            jpBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBotoesLayout.createSequentialGroup()
                .addContainerGap(593, Short.MAX_VALUE)
                .addComponent(jbImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpBotoesLayout.setVerticalGroup(
            jpBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpImpressaoCmei, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpImpressaoCmei, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbImprimirActionPerformed

        //ADOGeral ag = new ADOGeral();
        Conexao conexao = new Conexao();
        HashMap parametros = new HashMap();
        
        int filaEsperaBercario = 0;
        int filaEsperaMaternal1 = 0;
        int filaEsperaMaternal2 = 0;
        int filaEsperaMaternal3 = 0;
        int filaEsperaPre1 = 0;
        int filaEsperaPre2 = 0;
        int filaEsperaTotal = 0;
        int matriculadosBercario = 0;
        int matriculadosMaternal1 = 0;
        int matriculadosMaternal2 = 0;
        int matriculadosMaternal3 = 0;
        int matriculadosPre1 = 0;
        int matriculadosPre2 = 0;
        int matriculadosTotal = 0;
        int egressosBercario = 0;
        int egressosMaternal1 = 0;
        int egressosMaternal2 = 0;
        int egressosMaternal3 = 0;
        int egressosPre1 = 0;
        int egressosPre2 = 0;
        int egressosTotal = 0;
        int desistenciasBercario = 0;
        int desistenciasMaternal1 = 0;
        int desistenciasMaternal2 = 0;
        int desistenciasMaternal3 = 0;
        int desistenciasPre1 = 0;
        int desistenciasPre2 = 0;
        int desistenciasTotal = 0;
        String nomeCmei;
        
        iniciaDao();
        
        if (jrbTodosCmeis.isSelected()) {
            nomeCmei = "";
        } else {
            nomeCmei = jcbNomeEntidade.getSelectedItem().toString();
        }
        
        filaEsperaBercario = dao.getQuantidadeCadastro(nomeCmei, "FILA", "BERÇÁRIO");
        filaEsperaMaternal1 = dao.getQuantidadeCadastro(nomeCmei, "FILA", "MATERNAL I");
        filaEsperaMaternal2 = dao.getQuantidadeCadastro(nomeCmei, "FILA", "MATERNAL II");
        filaEsperaMaternal3 = dao.getQuantidadeCadastro(nomeCmei, "FILA", "MATERNAL III");
        filaEsperaPre1 = dao.getQuantidadeCadastro(nomeCmei, "FILA", "PRÉ I");
        filaEsperaPre2 = dao.getQuantidadeCadastro(nomeCmei, "FILA", "PRÉ II");
        filaEsperaTotal = dao.getQuantidadeCadastro(nomeCmei, "FILA", "");
        

        matriculadosBercario = dao.getQuantidadeCadastro(nomeCmei, "MATRICULA", "BERÇÁRIO");
        matriculadosMaternal1 = dao.getQuantidadeCadastro(nomeCmei, "MATRICULA", "MATERNAL I");
        matriculadosMaternal2 = dao.getQuantidadeCadastro(nomeCmei, "MATRICULA", "MATERNAL II");
        matriculadosMaternal3 = dao.getQuantidadeCadastro(nomeCmei, "MATRICULA", "MATERNAL III");
        matriculadosPre1 = dao.getQuantidadeCadastro(nomeCmei, "MATRICULA", "PRÉ I");
        matriculadosPre2 = dao.getQuantidadeCadastro(nomeCmei, "MATRICULA", "PRÉ II");
        matriculadosTotal = dao.getQuantidadeCadastro(nomeCmei, "MATRICULA", "");
        
        egressosBercario = dao.getQuantidadeCadastro(nomeCmei, "EGRESSO", "BERÇÁRIO");
        egressosMaternal1 = dao.getQuantidadeCadastro(nomeCmei, "EGRESSO", "MATERNAL I");
        egressosMaternal2 = dao.getQuantidadeCadastro(nomeCmei, "EGRESSO", "MATERNAL II");
        egressosMaternal3 = dao.getQuantidadeCadastro(nomeCmei, "EGRESSO", "MATERNAL III");
        egressosPre1 = dao.getQuantidadeCadastro(nomeCmei, "EGRESSO", "PRÉ I");
        egressosPre2 = dao.getQuantidadeCadastro(nomeCmei, "EGRESSO", "PRÉ II");
        egressosTotal = dao.getQuantidadeCadastro(nomeCmei, "EGRESSO", "");
        
        desistenciasBercario = dao.getQuantidadeCadastro(nomeCmei, "DESISTENCIA", "BERÇÁRIO");
        desistenciasMaternal1 = dao.getQuantidadeCadastro(nomeCmei, "DESISTENCIA", "MATERNAL I");
        desistenciasMaternal2 = dao.getQuantidadeCadastro(nomeCmei, "DESISTENCIA", "MATERNAL II");
        desistenciasMaternal3 = dao.getQuantidadeCadastro(nomeCmei, "DESISTENCIA", "MATERNAL III");
        desistenciasPre1 = dao.getQuantidadeCadastro(nomeCmei, "DESISTENCIA", "PRÉ I");
        desistenciasPre2 = dao.getQuantidadeCadastro(nomeCmei, "DESISTENCIA", "PRÉ II");
        desistenciasTotal = dao.getQuantidadeCadastro(nomeCmei, "DESISTENCIA", "");
        
        try {
            
            parametros.put("filaEsperaBercario", filaEsperaBercario);
            parametros.put("filaEsperaMaternal1", filaEsperaMaternal1);
            parametros.put("filaEsperaMaternal2", filaEsperaMaternal2);
            parametros.put("filaEsperaMaternal3", filaEsperaMaternal3);
            parametros.put("filaEsperaPre1", filaEsperaPre1);
            parametros.put("filaEsperaPre2", filaEsperaPre2);
            parametros.put("filaEsperaTotal", filaEsperaTotal);
            parametros.put("matriculadosBercario", matriculadosBercario);
            parametros.put("matriculadosMaternal1", matriculadosMaternal1);
            parametros.put("matriculadosMaternal2", matriculadosMaternal2);
            parametros.put("matriculadosMaternal3", matriculadosMaternal3);
            parametros.put("matriculadosPre1", matriculadosPre1);
            parametros.put("matriculadosPre2", matriculadosPre2);
            parametros.put("matriculadosTotal", matriculadosTotal);
            parametros.put("egressosBercario", egressosBercario);
            parametros.put("egressosMaternal1", egressosMaternal1);
            parametros.put("egressosMaternal2", egressosMaternal2);
            parametros.put("egressosMaternal3", egressosMaternal3);
            parametros.put("egressosPre1", egressosPre1);
            parametros.put("egressosPre2", egressosPre2);
            parametros.put("egressosTotal", egressosTotal);
            parametros.put("desistenciasBercario", desistenciasBercario);
            parametros.put("desistenciasMaternal1", desistenciasMaternal1);
            parametros.put("desistenciasMaternal2", desistenciasMaternal2);
            parametros.put("desistenciasMaternal3", desistenciasMaternal3);
            parametros.put("desistenciasPre1", desistenciasPre1);
            parametros.put("desistenciasPre2", desistenciasPre2);
            parametros.put("desistenciasTotal", desistenciasTotal);
            conexao.getConexao();
            
        } catch (ExcCadastro ex) {
            Logger.getLogger(jfImpressosRelatorio.class.getName()).log(Level.SEVERE, null, ex);
        }

        //        JRDataSource jrds = new JRBeanCollectionDataSource(lista);

        try {

            //jReport = JasperCompileManager.compileReport("E:/LUIZ/PROJETOS JAVA/CORPORATIVO/m2GestaoClinicas/FichaPaciente.jrxml");
            //jPrint = JasperFillManager.fillReport("C:/m2GestaoClinicas/FichaPaciente.jasper", parametros, ADOGeral.getConexao());
            if (jrbTodosCmeis.isSelected()) {

                //parametros.put("nomeCmei", jcbNomeEntidade.getSelectedItem().toString());
                jPrint = JasperFillManager.fillReport("RelatorioFilaEsperaMatricula.jasper", parametros, conexao.getConexao());

            } else if(jrbPorCmei.isSelected()) {

                if (jcbNomeEntidade.getSelectedIndex() == 0) {
                    JOptionPane.showMessageDialog(null, "Não há nenhuma Entidade selecinada no campo especifico!", "Atenção", JOptionPane.WARNING_MESSAGE, null);
                } else {
                    parametros.put("nomeCmei", jcbNomeEntidade.getSelectedItem().toString());
                    jPrint = JasperFillManager.fillReport("RelatorioFilaEsperaMatriculaPorCmei.jasper", parametros, conexao.getConexao());
                }

            }

            //jPrint = JasperFillManager.fillReport(jReport, parametros, jrds);

            //if (!(jViewer == null)) {
            //jViewer = new JasperViewer(jPrint, false);
            //jViewer.setExtendedState(JFrame.MAXIMIZED_BOTH);
            if (jPrint != null) {
                jViewer.viewReport(jPrint, false);
                jPrint = null;
            }
            //}

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_jbImprimirActionPerformed

    private void jrbTodosCmeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbTodosCmeisActionPerformed

        if (jrbTodosCmeis.isSelected()) {
            jcbNomeEntidade.setEnabled(false);
        }

    }//GEN-LAST:event_jrbTodosCmeisActionPerformed

    private void jrbPorCmeiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbPorCmeiActionPerformed

        if (jrbPorCmei.isSelected()) {
            jcbNomeEntidade.setEnabled(true);
            preencheComboCmeis();
        }

    }//GEN-LAST:event_jrbPorCmeiActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        fechar();
    }//GEN-LAST:event_formWindowClosing

    /**
    * @param args the command line arguments
    */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfImpressosCmei().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgImpressosCmei;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbImprimir;
    private javax.swing.JComboBox jcbNomeEntidade;
    private javax.swing.JPanel jpBotoes;
    private javax.swing.JPanel jpImpressaoCmei;
    private javax.swing.JRadioButton jrbPorCmei;
    private javax.swing.JRadioButton jrbTodosCmeis;
    // End of variables declaration//GEN-END:variables

//Outros Metodos ===========================================================================================================================================
    public void fechar() {
        this.dispose();
    }

    public void preencheComboCmeis() {

        DAO dao = new DAO();
        List listaCmeis = new ArrayList();

        jcbNomeEntidade.removeAllItems();
        jcbNomeEntidade.addItem("");

        listaCmeis = dao.listarCmeis();

        for (int i = 0; i < listaCmeis.size(); i++) {
            jcbNomeEntidade.addItem(listaCmeis.get(i));
        }

    }
    
//Geradores, Validadores===========================================================================================================================================
    public void abilitaBotoes() {

        if (imprimirCmei == true) {
            jbImprimir.setEnabled(true);
        } else {
            jbImprimir.setEnabled(false);
        }

    }

    public void desabilitaBotoes() {

        if (imprimirCmei == true) {
            jbImprimir.setEnabled(true);
        } else {
            jbImprimir.setEnabled(false);
        }

    }
    
    public void iniciaDao() {
        
        if (dao == null) {
            dao = new DAO();
        }
        
    }

//Getters and Setters===========================================================================================================================================
    public String getNomeUsuario() {
        return nomeUsuario;
    }

    public void setNomeUsuario(String nomeUsuario) {
        this.nomeUsuario = nomeUsuario;
        getPermissoes();
        desabilitaBotoes();
    }

    public void getPermissoes() {
        Permissoes permissoes;
        DAO dao = new DAO();

        permissoes = (Permissoes) dao.buscaPermissoes(getNomeUsuario());

        imprimirCmei = permissoes.isImprimirCmei();
    }

//Metodos DAO===========================================================================================================================================

}
