/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jfPrincipal.java
 *
 * Created on 04/08/2010, 10:54:45
 */

package visual;

import controlador.ControleImagem;
import controlador.ControleVersao;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;

/**
 *
 * @author luizam
 */
public class jfPrincipal extends javax.swing.JFrame {

    private static ControleVersao versao = new ControleVersao();
    private jfCadastroAluno jfCadAluno;
    private jfCadastroCmei jfCadCmei;
    private jfCadastroFuncaoCargo jfCadFuncaoCargo;
    private jfCadastroLicenca jfCadLicenca;
    private jfCadastroRestricao jfCadRestricao;
    private jfCadastroServidor jfCadServidor;
    private jfCadastroUsuario jfCadUsuario;
    private jfImpressosCmei jfImpreCmei;
    private jfImpressosAlunos jfImpreAlunos;
    private jfImpressosRelatorio jfImpreRelatorio;
    private jfVisualizaTransferenciasAluno jfVisuTransAlun;
    private jfVisualizarQuadroPessoalCmei jfVisuQuadroPessoalCmei;
    private jfVisualizarQuadroFuncionalCmei jfVisuQuadroFuncionalCmei;
    private jfSobre jfSob;
    private ControleImagem controleImagem = new ControleImagem();

    private String nomeUsuario;
    private String tipoCadastroUsuario;

    /** Creates new form jfPrincipal */
    public jfPrincipal() {
        super("CADUN - " + versao.getVersao() + " - " + versao.getAno());
        initComponents();

        //Altera icone na barra de titulo
        Toolkit kit = Toolkit.getDefaultToolkit();
        Image img = kit.getImage(controleImagem.getIconeImagem());
        this.setIconImage(img);

        //maximiza tela
        this.setExtendedState(MAXIMIZED_BOTH);

        //centraliza tela
        setSize(getWidth(), getHeight());
        setLocationRelativeTo(null);
        
        jlbVersao.setText(versao.getVersao());
        jpVersaoNova.setVisible(false);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpVersaoNova = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlbVersao = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jmbPrincipal = new javax.swing.JMenuBar();
        jmArquivos = new javax.swing.JMenu();
        jmiSair = new javax.swing.JMenuItem();
        jmCadastros = new javax.swing.JMenu();
        jmiCmei = new javax.swing.JMenuItem();
        jmiFuncaoCargo = new javax.swing.JMenuItem();
        jmiAluno = new javax.swing.JMenuItem();
        jmiUsuario = new javax.swing.JMenuItem();
        jmiServidor = new javax.swing.JMenuItem();
        jmiLicenca = new javax.swing.JMenuItem();
        jmiRestricao = new javax.swing.JMenuItem();
        jmVisualizar = new javax.swing.JMenu();
        jmiVisualizarQuadroPessoal = new javax.swing.JMenuItem();
        jmiVisualizarQuadroFuncional = new javax.swing.JMenuItem();
        jmiVisualizarTransferenciaAluno = new javax.swing.JMenuItem();
        jmImpressos = new javax.swing.JMenu();
        jmiImprCmei = new javax.swing.JMenuItem();
        jmiImprAluno = new javax.swing.JMenuItem();
        jmiRelatorio = new javax.swing.JMenuItem();
        jmSobre = new javax.swing.JMenu();
        jmiSobre = new javax.swing.JMenuItem();
        jmiPainelAlteracoes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jpVersaoNova.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpVersaoNova.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpVersaoNovaMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("A versão ");

        jlbVersao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbVersao.setText("versão");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("traz de novo os itens abaixo:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("1 - Módulo para trasferência de Servidor de um CMEI para outro;");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("2 - Módulo para trasferência de Aluno de um CMEI para outro;");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("3 - As Tabelas das buscas podem ser ordenadas em ordem alfabética,");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("quando clicado na coluna pela qual deseja ordenar.");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("4 - É possivel imprimir um relatório com a quantidade de alunos matricula-");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("dos, egressos, desistentes e na fila de espera, por CMEI ou geral, na ");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("guia Impressos - Relatórios.");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("5 - Para inserir um usuário é necessário digitar a senha, do mesmo, em");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("dois campos diferentes, \"Senha\" e \"Confirma Senha\", para confirmar ");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("que é mesmo a senha desejada.");

        javax.swing.GroupLayout jpVersaoNovaLayout = new javax.swing.GroupLayout(jpVersaoNova);
        jpVersaoNova.setLayout(jpVersaoNovaLayout);
        jpVersaoNovaLayout.setHorizontalGroup(
            jpVersaoNovaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVersaoNovaLayout.createSequentialGroup()
                .addGroup(jpVersaoNovaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpVersaoNovaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbVersao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(jpVersaoNovaLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jpVersaoNovaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpVersaoNovaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jpVersaoNovaLayout.setVerticalGroup(
            jpVersaoNovaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVersaoNovaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpVersaoNovaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jlbVersao)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jmArquivos.setText("Arquivo");

        jmiSair.setText("Sair");
        jmiSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSairActionPerformed(evt);
            }
        });
        jmArquivos.add(jmiSair);

        jmbPrincipal.add(jmArquivos);

        jmCadastros.setText("Cadastros");

        jmiCmei.setText("CMEI");
        jmiCmei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCmeiActionPerformed(evt);
            }
        });
        jmCadastros.add(jmiCmei);

        jmiFuncaoCargo.setText("Função/Cargo");
        jmiFuncaoCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFuncaoCargoActionPerformed(evt);
            }
        });
        jmCadastros.add(jmiFuncaoCargo);

        jmiAluno.setText("Alunos");
        jmiAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAlunoActionPerformed(evt);
            }
        });
        jmCadastros.add(jmiAluno);

        jmiUsuario.setText("Usuário");
        jmiUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUsuarioActionPerformed(evt);
            }
        });
        jmCadastros.add(jmiUsuario);

        jmiServidor.setText("Servidor");
        jmiServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiServidorActionPerformed(evt);
            }
        });
        jmCadastros.add(jmiServidor);

        jmiLicenca.setText("Licença");
        jmiLicenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLicencaActionPerformed(evt);
            }
        });
        jmCadastros.add(jmiLicenca);

        jmiRestricao.setText("Restrição");
        jmiRestricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRestricaoActionPerformed(evt);
            }
        });
        jmCadastros.add(jmiRestricao);

        jmbPrincipal.add(jmCadastros);

        jmVisualizar.setText("Visualizar");

        jmiVisualizarQuadroPessoal.setText("Quadro Pessoal do CMEI");
        jmiVisualizarQuadroPessoal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiVisualizarQuadroPessoalActionPerformed(evt);
            }
        });
        jmVisualizar.add(jmiVisualizarQuadroPessoal);

        jmiVisualizarQuadroFuncional.setText("Quadro Funcional do CMEI");
        jmiVisualizarQuadroFuncional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiVisualizarQuadroFuncionalActionPerformed(evt);
            }
        });
        jmVisualizar.add(jmiVisualizarQuadroFuncional);

        jmiVisualizarTransferenciaAluno.setText("Transferência de Aluno");
        jmiVisualizarTransferenciaAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiVisualizarTransferenciaAlunoActionPerformed(evt);
            }
        });
        jmVisualizar.add(jmiVisualizarTransferenciaAluno);

        jmbPrincipal.add(jmVisualizar);

        jmImpressos.setText("Impressos");

        jmiImprCmei.setText("CMEI");
        jmiImprCmei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiImprCmeiActionPerformed(evt);
            }
        });
        jmImpressos.add(jmiImprCmei);

        jmiImprAluno.setText("Aluno");
        jmiImprAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiImprAlunoActionPerformed(evt);
            }
        });
        jmImpressos.add(jmiImprAluno);

        jmiRelatorio.setText("Relatório");
        jmiRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRelatorioActionPerformed(evt);
            }
        });
        jmImpressos.add(jmiRelatorio);

        jmbPrincipal.add(jmImpressos);

        jmSobre.setText("Sobre");

        jmiSobre.setText("Sobre");
        jmiSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSobreActionPerformed(evt);
            }
        });
        jmSobre.add(jmiSobre);

        jmiPainelAlteracoes.setText("Painel de Alterações");
        jmiPainelAlteracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPainelAlteracoesActionPerformed(evt);
            }
        });
        jmSobre.add(jmiPainelAlteracoes);

        jmbPrincipal.add(jmSobre);

        setJMenuBar(jmbPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpVersaoNova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(637, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jpVersaoNova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(329, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSairActionPerformed
        fechar();
    }//GEN-LAST:event_jmiSairActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        fechar();
    }//GEN-LAST:event_formWindowClosing

    private void jmiCmeiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCmeiActionPerformed
        if (jfCadCmei == null) {
            jfCadCmei = new jfCadastroCmei();
        }

        jfCadCmei.setNomeUsuario(nomeUsuario);
        jfCadCmei.setVisible(true);
    }//GEN-LAST:event_jmiCmeiActionPerformed

    private void jmiFuncaoCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFuncaoCargoActionPerformed
        if (jfCadFuncaoCargo == null) {
            jfCadFuncaoCargo = new jfCadastroFuncaoCargo();
        }

        jfCadFuncaoCargo.setNomeUsuario(nomeUsuario);
        jfCadFuncaoCargo.setVisible(true);
    }//GEN-LAST:event_jmiFuncaoCargoActionPerformed

    private void jmiAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAlunoActionPerformed
        if (jfCadAluno == null) {
            jfCadAluno = new jfCadastroAluno();
        }

        jfCadAluno.setTipoCadastroUsuario(tipoCadastroUsuario);
        jfCadAluno.setNomeUsuario(nomeUsuario);
        jfCadAluno.setVisible(true);
    }//GEN-LAST:event_jmiAlunoActionPerformed

    private void jmiUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUsuarioActionPerformed
        if (jfCadUsuario == null) {
            jfCadUsuario = new jfCadastroUsuario();
        }

        jfCadUsuario.setTipoCadastroUsuario(tipoCadastroUsuario);
        jfCadUsuario.setNomeUsuario(nomeUsuario);
        //jfCadUsuario.setTipoContraSenha(tipoContraSenha);
        jfCadUsuario.setVisible(true);
    }//GEN-LAST:event_jmiUsuarioActionPerformed

    private void jmiImprCmeiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiImprCmeiActionPerformed
        if (jfImpreCmei == null) {
            jfImpreCmei = new jfImpressosCmei();
        }

        jfImpreCmei.setNomeUsuario(nomeUsuario);
        jfImpreCmei.setVisible(true);
    }//GEN-LAST:event_jmiImprCmeiActionPerformed

    private void jmiImprAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiImprAlunoActionPerformed
        if (jfImpreAlunos == null) {
            jfImpreAlunos = new jfImpressosAlunos();
        }

        jfImpreAlunos.setNomeUsuario(nomeUsuario);
        jfImpreAlunos.setVisible(true);
    }//GEN-LAST:event_jmiImprAlunoActionPerformed

    private void jmiVisualizarQuadroPessoalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiVisualizarQuadroPessoalActionPerformed
        if (jfVisuQuadroPessoalCmei == null) {
            jfVisuQuadroPessoalCmei = new jfVisualizarQuadroPessoalCmei();
        }

        jfVisuQuadroPessoalCmei.setNomeUsuario(nomeUsuario);
        jfVisuQuadroPessoalCmei.setVisible(true);
    }//GEN-LAST:event_jmiVisualizarQuadroPessoalActionPerformed

    private void jmiServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiServidorActionPerformed
        if (jfCadServidor == null) {
            jfCadServidor = new jfCadastroServidor();
        }

        jfCadServidor.setTipoCadastroUsuario(tipoCadastroUsuario);
        jfCadServidor.setNomeUsuario(nomeUsuario);
        jfCadServidor.setVisible(true);
    }//GEN-LAST:event_jmiServidorActionPerformed

    private void jmiVisualizarQuadroFuncionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiVisualizarQuadroFuncionalActionPerformed
        if (jfVisuQuadroFuncionalCmei == null) {
            jfVisuQuadroFuncionalCmei = new jfVisualizarQuadroFuncionalCmei();
        }

        jfVisuQuadroFuncionalCmei.setNomeUsuario(nomeUsuario);
        jfVisuQuadroFuncionalCmei.setVisible(true);
    }//GEN-LAST:event_jmiVisualizarQuadroFuncionalActionPerformed

    private void jmiSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSobreActionPerformed
        if (jfSob == null) {
            jfSob = new jfSobre();
        }

        jfSob.setNomeUsuario(nomeUsuario);
        jfSob.setVisible(true);
    }//GEN-LAST:event_jmiSobreActionPerformed

    private void jmiRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRelatorioActionPerformed
        
        if (jfImpreRelatorio == null) {
            jfImpreRelatorio = new jfImpressosRelatorio();
        }
        
        jfImpreRelatorio.setVisible(true);
        
    }//GEN-LAST:event_jmiRelatorioActionPerformed

    private void jmiVisualizarTransferenciaAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiVisualizarTransferenciaAlunoActionPerformed
        
        if (jfVisuTransAlun == null) {
            jfVisuTransAlun = new jfVisualizaTransferenciasAluno();
        }
        
        jfVisuTransAlun.setVisible(true);
        
    }//GEN-LAST:event_jmiVisualizarTransferenciaAlunoActionPerformed

    private void jpVersaoNovaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpVersaoNovaMouseClicked
        jpVersaoNova.setVisible(false);
    }//GEN-LAST:event_jpVersaoNovaMouseClicked

    private void jmiPainelAlteracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPainelAlteracoesActionPerformed
        jpVersaoNova.setVisible(true);
    }//GEN-LAST:event_jmiPainelAlteracoesActionPerformed

    private void jmiRestricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRestricaoActionPerformed
        
        if (jfCadRestricao == null) {
            jfCadRestricao = new jfCadastroRestricao();
        }
        
        jfCadRestricao.setNomeUsuario(nomeUsuario);
        jfCadRestricao.setVisible(true);
        
    }//GEN-LAST:event_jmiRestricaoActionPerformed

    private void jmiLicencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiLicencaActionPerformed
        
        if (jfCadLicenca == null) {
            jfCadLicenca = new jfCadastroLicenca();
        }
        
        jfCadLicenca.setNomeUsuario(nomeUsuario);
        jfCadLicenca.setVisible(true);
        
    }//GEN-LAST:event_jmiLicencaActionPerformed

    /**
    * @param args the command line arguments
    */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfPrincipal().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jlbVersao;
    private javax.swing.JMenu jmArquivos;
    private javax.swing.JMenu jmCadastros;
    private javax.swing.JMenu jmImpressos;
    private javax.swing.JMenu jmSobre;
    private javax.swing.JMenu jmVisualizar;
    private javax.swing.JMenuBar jmbPrincipal;
    private javax.swing.JMenuItem jmiAluno;
    private javax.swing.JMenuItem jmiCmei;
    private javax.swing.JMenuItem jmiFuncaoCargo;
    private javax.swing.JMenuItem jmiImprAluno;
    private javax.swing.JMenuItem jmiImprCmei;
    private javax.swing.JMenuItem jmiLicenca;
    private javax.swing.JMenuItem jmiPainelAlteracoes;
    private javax.swing.JMenuItem jmiRelatorio;
    private javax.swing.JMenuItem jmiRestricao;
    private javax.swing.JMenuItem jmiSair;
    private javax.swing.JMenuItem jmiServidor;
    private javax.swing.JMenuItem jmiSobre;
    private javax.swing.JMenuItem jmiUsuario;
    private javax.swing.JMenuItem jmiVisualizarQuadroFuncional;
    private javax.swing.JMenuItem jmiVisualizarQuadroPessoal;
    private javax.swing.JMenuItem jmiVisualizarTransferenciaAluno;
    private javax.swing.JPanel jpVersaoNova;
    // End of variables declaration//GEN-END:variables

//Outros Metodos ===========================================================================================================================================
    public void fechar() {
        this.dispose();
    }

//Geradores, Validadores===========================================================================================================================================
    
//Getters and Setters===========================================================================================================================================
    public void setTemaEscolhido(String temaEscolhido) {

        if (temaEscolhido.equals("PADRÃO")) {
        } else if (temaEscolhido.equals("LIQUIDO")) {

            try {
                UIManager.setLookAndFeel("com.birosoft.liquid.LiquidLookAndFeel");
                SwingUtilities.updateComponentTreeUI(this);
            } catch (Exception ex) {
                System.out.println(ex.getMessage());
            }

        } else if (temaEscolhido.equals("WINDOWS")) {

            //Visual estilo Windows
            LookAndFeelInfo[] laf = UIManager.getInstalledLookAndFeels();
            for (int i = 0; i < laf.length; i++) {
                System.out.println(laf[i].getName());
                if (laf[i].getName().equals("Windows")) {
                    try {
                        UIManager.setLookAndFeel(laf[i].getClassName());
                        SwingUtilities.updateComponentTreeUI(this);
                    } catch (Exception e) {
                    }
                }
                if (laf[i].getName().equals("GTK+")) {
                    try {
                        UIManager.setLookAndFeel(laf[i].getClassName());
                        SwingUtilities.updateComponentTreeUI(this);
                    } catch (Exception e) {
                    }
                }
            }

        }

    }

    public String getTipoCadastroUsuario() {
        return tipoCadastroUsuario;
    }

    public void setTipoCadastroUsuario(String tipoCadastroUsuario) {
        this.tipoCadastroUsuario = tipoCadastroUsuario;
    }

    public String getNomeUsuario() {
        return nomeUsuario;
    }

    public void setNomeUsuario(String nomeUsuario) {
        this.nomeUsuario = nomeUsuario;
    }
//Metodos DAO===========================================================================================================================================
}
