/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jfVisualizarCmei.java
 *
 * Created on 16/08/2010, 14:37:01
 */
package visual;

import conexao.Conexao;
import controlador.ControleImagem;
import controlador.ControleVersao;
import dao.DAO;
import excecoes.ExcCadastro;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cmei;
import modelo.Servidor;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author luizam
 */
public class jfVisualizarQuadroPessoalCmei extends javax.swing.JFrame {

    private static ControleVersao versao = new ControleVersao();
    private ControleImagem controleImagem = new ControleImagem();
    
    private JasperPrint jPrint;
    private JasperViewer jViewer;
    
    private int codigo;
    private String nomeUsuario;

    /** Creates new form jfVisualizarCmei */
    public jfVisualizarQuadroPessoalCmei() {
        super("Informações dos CMEI's - Quadro Pessoal - " + versao.getVersao() + " - " + versao.getAno());
        initComponents();

        //Altera icone na barra de titulo
        Toolkit kit = Toolkit.getDefaultToolkit();
        Image img = kit.getImage(controleImagem.getIconeImagem());
        this.setIconImage(img);

        //centraliza tela
        setSize(getWidth(), getHeight());
        setLocationRelativeTo(null);
        setVisible(true);

        desabilitaCampos();

        preencheComboCmeis();

        setCamposParaZero();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpInformacoesCmei = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcbNomeEntidade = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtfCoordenador = new javax.swing.JTextField();
        jtfCapacidadeAlunos = new javax.swing.JTextField();
        jtfVagasDisponiveis = new javax.swing.JTextField();
        jtfServidoresConcursados = new javax.swing.JTextField();
        jtfEstagiarios = new javax.swing.JTextField();
        jtfNumeroLotacoes = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbVisualizarQuadroPessoal = new javax.swing.JTable();
        jpQuantitativo = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jlbNrSalasPre = new javax.swing.JLabel();
        jlbNrSalasMaternal = new javax.swing.JLabel();
        jlbNrSalasBercario = new javax.swing.JLabel();
        jlbNrSalasTotal = new javax.swing.JLabel();
        jlbNrAlunosPre = new javax.swing.JLabel();
        jlbNrAlunosMaternal = new javax.swing.JLabel();
        jlbNrAlunosBercario = new javax.swing.JLabel();
        jlbNrAlunosTotal = new javax.swing.JLabel();
        jlbNrMonitoresPre = new javax.swing.JLabel();
        jlbNrMonitoresMaternal = new javax.swing.JLabel();
        jlbNrMonitoresBercario = new javax.swing.JLabel();
        jlbNrMonitoresTotal = new javax.swing.JLabel();
        jlbNrEstagiariosPre = new javax.swing.JLabel();
        jlbNrEstagiariosMaternal = new javax.swing.JLabel();
        jlbNrEstagiariosBercario = new javax.swing.JLabel();
        jlbNrEstagiariosTotal = new javax.swing.JLabel();
        jlbNrProfessoresPre = new javax.swing.JLabel();
        jlbNrProfessoresMaternal = new javax.swing.JLabel();
        jlbNrProfessoresBercario = new javax.swing.JLabel();
        jlbNrProfessoresTotal = new javax.swing.JLabel();
        jpBotoes = new javax.swing.JPanel();
        jbFechar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jbImprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jpInformacoesCmei.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Nome do CMEI: ");

        jcbNomeEntidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbNomeEntidade.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jcbNomeEntidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbNomeEntidadeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Cooredenador(a): ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Capacidade de alunos: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Vagas Disponíveis: ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Servidores Concursados: ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Estagiários: ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Total Lotações: ");

        jtfCoordenador.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfCoordenador.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jtfCapacidadeAlunos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfCapacidadeAlunos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jtfVagasDisponiveis.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfVagasDisponiveis.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jtfServidoresConcursados.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfServidoresConcursados.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jtfEstagiarios.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfEstagiarios.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jtfNumeroLotacoes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfNumeroLotacoes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jtbVisualizarQuadroPessoal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jtbVisualizarQuadroPessoal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtbVisualizarQuadroPessoal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome do Servidor", "Função / Cargo", "Modalidade", "Matrícula"
            }
        ));
        jtbVisualizarQuadroPessoal.setGridColor(new java.awt.Color(204, 204, 204));
        jtbVisualizarQuadroPessoal.setRowHeight(19);
        jtbVisualizarQuadroPessoal.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtbVisualizarQuadroPessoal.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtbVisualizarQuadroPessoal);

        jpQuantitativo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("MODALIDADES");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("SALAS");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("ALUNOS");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("MONITORES");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("ESTAGIÁRIOS");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("PROFESSORES");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("PRÉ");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("MATERNAL");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("BERÇÁRIO");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("TOTAL");

        jlbNrSalasPre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbNrSalasPre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbNrSalasPre.setText("nrSalas");

        jlbNrSalasMaternal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbNrSalasMaternal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbNrSalasMaternal.setText("nrSalas");

        jlbNrSalasBercario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbNrSalasBercario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbNrSalasBercario.setText("nrSalas");

        jlbNrSalasTotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbNrSalasTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbNrSalasTotal.setText("nrSalas");

        jlbNrAlunosPre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbNrAlunosPre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbNrAlunosPre.setText("nrAlunos");

        jlbNrAlunosMaternal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbNrAlunosMaternal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbNrAlunosMaternal.setText("nrAlunos");

        jlbNrAlunosBercario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbNrAlunosBercario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbNrAlunosBercario.setText("nrAlunos");

        jlbNrAlunosTotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbNrAlunosTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbNrAlunosTotal.setText("nrAlunos");

        jlbNrMonitoresPre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbNrMonitoresPre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbNrMonitoresPre.setText("nrMonitores");

        jlbNrMonitoresMaternal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbNrMonitoresMaternal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbNrMonitoresMaternal.setText("nrMonitores");

        jlbNrMonitoresBercario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbNrMonitoresBercario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbNrMonitoresBercario.setText("nrMonitores");

        jlbNrMonitoresTotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbNrMonitoresTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbNrMonitoresTotal.setText("nrMonitores");

        jlbNrEstagiariosPre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbNrEstagiariosPre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbNrEstagiariosPre.setText("nrEstagiários");

        jlbNrEstagiariosMaternal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbNrEstagiariosMaternal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbNrEstagiariosMaternal.setText("nrEstagiários");

        jlbNrEstagiariosBercario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbNrEstagiariosBercario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbNrEstagiariosBercario.setText("nrEstagiários");

        jlbNrEstagiariosTotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbNrEstagiariosTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbNrEstagiariosTotal.setText("nrEstagiários");

        jlbNrProfessoresPre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbNrProfessoresPre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbNrProfessoresPre.setText("nrProfessores");

        jlbNrProfessoresMaternal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbNrProfessoresMaternal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbNrProfessoresMaternal.setText("nrProfessores");

        jlbNrProfessoresBercario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbNrProfessoresBercario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbNrProfessoresBercario.setText("nrProfessores");

        jlbNrProfessoresTotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbNrProfessoresTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbNrProfessoresTotal.setText("nrProfessores");

        javax.swing.GroupLayout jpQuantitativoLayout = new javax.swing.GroupLayout(jpQuantitativo);
        jpQuantitativo.setLayout(jpQuantitativoLayout);
        jpQuantitativoLayout.setHorizontalGroup(
            jpQuantitativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpQuantitativoLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jpQuantitativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addGroup(jpQuantitativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlbNrSalasBercario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbNrSalasMaternal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbNrSalasPre, 0, 1, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbNrSalasTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jpQuantitativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpQuantitativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jlbNrAlunosBercario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlbNrAlunosMaternal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlbNrAlunosPre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10))
                    .addComponent(jlbNrAlunosTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpQuantitativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlbNrMonitoresTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbNrMonitoresBercario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbNrMonitoresMaternal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbNrMonitoresPre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jpQuantitativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlbNrEstagiariosTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbNrEstagiariosBercario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbNrEstagiariosMaternal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbNrEstagiariosPre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jpQuantitativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlbNrProfessoresTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbNrProfessoresBercario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbNrProfessoresMaternal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbNrProfessoresPre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jpQuantitativoLayout.setVerticalGroup(
            jpQuantitativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpQuantitativoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpQuantitativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpQuantitativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jlbNrSalasPre)
                    .addComponent(jlbNrAlunosPre)
                    .addComponent(jlbNrMonitoresPre)
                    .addComponent(jlbNrEstagiariosPre)
                    .addComponent(jlbNrProfessoresPre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpQuantitativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jlbNrSalasMaternal)
                    .addComponent(jlbNrAlunosMaternal)
                    .addComponent(jlbNrMonitoresMaternal)
                    .addComponent(jlbNrEstagiariosMaternal)
                    .addComponent(jlbNrProfessoresMaternal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpQuantitativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jlbNrSalasBercario)
                    .addComponent(jlbNrAlunosBercario)
                    .addComponent(jlbNrMonitoresBercario)
                    .addComponent(jlbNrEstagiariosBercario)
                    .addComponent(jlbNrProfessoresBercario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpQuantitativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jlbNrAlunosTotal)
                    .addComponent(jlbNrMonitoresTotal)
                    .addComponent(jlbNrEstagiariosTotal)
                    .addComponent(jlbNrProfessoresTotal)
                    .addComponent(jlbNrSalasTotal))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpInformacoesCmeiLayout = new javax.swing.GroupLayout(jpInformacoesCmei);
        jpInformacoesCmei.setLayout(jpInformacoesCmeiLayout);
        jpInformacoesCmeiLayout.setHorizontalGroup(
            jpInformacoesCmeiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpInformacoesCmeiLayout.createSequentialGroup()
                .addGroup(jpInformacoesCmeiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpInformacoesCmeiLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpInformacoesCmeiLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jpInformacoesCmeiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpInformacoesCmeiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpInformacoesCmeiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtfCoordenador)
                                .addComponent(jcbNomeEntidade, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpInformacoesCmeiLayout.createSequentialGroup()
                                .addGroup(jpInformacoesCmeiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtfNumeroLotacoes, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfServidoresConcursados, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfCapacidadeAlunos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpInformacoesCmeiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpInformacoesCmeiLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfVagasDisponiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jpInformacoesCmeiLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfEstagiarios, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jpInformacoesCmeiLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpQuantitativo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpInformacoesCmeiLayout.setVerticalGroup(
            jpInformacoesCmeiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInformacoesCmeiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpInformacoesCmeiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcbNomeEntidade, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpInformacoesCmeiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfCoordenador, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpInformacoesCmeiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfCapacidadeAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jtfVagasDisponiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpInformacoesCmeiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfServidoresConcursados, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jtfEstagiarios, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpInformacoesCmeiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtfNumeroLotacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpQuantitativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpBotoes.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());

        jbFechar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbFechar.setText("Fechar");
        jbFechar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFecharActionPerformed(evt);
            }
        });

        jbCancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbImprimir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imprimir.png"))); // NOI18N
        jbImprimir.setText("Imprimir");
        jbImprimir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpBotoesLayout = new javax.swing.GroupLayout(jpBotoes);
        jpBotoes.setLayout(jpBotoesLayout);
        jpBotoesLayout.setHorizontalGroup(
            jpBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBotoesLayout.createSequentialGroup()
                .addContainerGap(398, Short.MAX_VALUE)
                .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpBotoesLayout.setVerticalGroup(
            jpBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpInformacoesCmei, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpInformacoesCmei, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cancelar();
        fechar();
    }//GEN-LAST:event_formWindowClosing

    private void jcbNomeEntidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbNomeEntidadeActionPerformed

        if (jcbNomeEntidade.getSelectedIndex() == 0) {
        } else {
            buscaCmei();
            buscaQuadroPessoal();
            buscaQuantitativos();
        }

    }//GEN-LAST:event_jcbNomeEntidadeActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        cancelar();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFecharActionPerformed
        cancelar();
        fechar();
    }//GEN-LAST:event_jbFecharActionPerformed

    private void jbImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbImprimirActionPerformed

        //ADOGeral ag = new ADOGeral();
        Conexao conexao = new Conexao();
        HashMap parametros = new HashMap();

        if (jcbNomeEntidade.getSelectedIndex() == 0) {

            JOptionPane.showMessageDialog(this, "Não há nenhuma Entidade selecinada no campo especifico!", "Atenção", JOptionPane.WARNING_MESSAGE, null);

        } else {

            try {
                //System.out.println(codigoRegistro);
                //parametros.put("titulo", "Titulo Relatorio");
                parametros.put("codigoCmei", new Integer(codigo));
                parametros.put("nomeCmei", new String(jcbNomeEntidade.getSelectedItem().toString()));
                parametros.put("nrSalasBercario", new String(jlbNrSalasBercario.getText()));
                parametros.put("nrSalasMaternal", new String(jlbNrSalasMaternal.getText()));
                parametros.put("nrSalasPre", new String(jlbNrSalasPre.getText()));
                parametros.put("nrSalasTotal", new String(jlbNrSalasTotal.getText()));
                parametros.put("nrAlunosBercario", new String(jlbNrAlunosBercario.getText()));
                parametros.put("nrAlunosMaternal", new String(jlbNrAlunosMaternal.getText()));
                parametros.put("nrAlunosPre", new String(jlbNrAlunosPre.getText()));
                parametros.put("nrAlunosTotal", new String(jlbNrAlunosTotal.getText()));
                parametros.put("nrMonitoresBercario", new String(jlbNrMonitoresBercario.getText()));
                parametros.put("nrMonitoresMaternal", new String(jlbNrMonitoresMaternal.getText()));
                parametros.put("nrMonitoresPre", new String(jlbNrMonitoresPre.getText()));
                parametros.put("nrMonitoresTotal", new String(jlbNrMonitoresTotal.getText()));
                parametros.put("nrEstagiariosBercario", new String(jlbNrEstagiariosBercario.getText()));
                parametros.put("nrEstagiariosMaternal", new String(jlbNrEstagiariosMaternal.getText()));
                parametros.put("nrEstagiariosPre", new String(jlbNrEstagiariosPre.getText()));
                parametros.put("nrEstagiariosTotal", new String(jlbNrEstagiariosTotal.getText()));
                parametros.put("nrProfessoresBercario", new String(jlbNrProfessoresBercario.getText()));
                parametros.put("nrProfessoresMaternal", new String(jlbNrProfessoresMaternal.getText()));
                parametros.put("nrProfessoresPre", new String(jlbNrProfessoresPre.getText()));
                parametros.put("nrProfessoresTotal", new String(jlbNrProfessoresTotal.getText()));
                //parametros.put("", evt);


                //parametros.put("mesInicio", jDateChooserInicio.getDate());
                //parametros.put("mesTermino", jDateChooserTermino.getDate());
                //parametros.put("codigo", lista.get(0).getNome();
                //ADOGeral.conectar();
                conexao.getConexao();
            } catch (ExcCadastro ex) {
                Logger.getLogger(jfImpressosCmei.class.getName()).log(Level.SEVERE, null, ex);
            }

            //        JRDataSource jrds = new JRBeanCollectionDataSource(lista);

            try {

                //jReport = JasperCompileManager.compileReport("E:/LUIZ/PROJETOS JAVA/CORPORATIVO/m2GestaoClinicas/FichaPaciente.jrxml");
                //jPrint = JasperFillManager.fillReport("C:/m2GestaoClinicas/FichaPaciente.jasper", parametros, ADOGeral.getConexao());

                jPrint = JasperFillManager.fillReport("QuadroPessoal.jasper", parametros, conexao.getConexao());

                //jPrint = JasperFillManager.fillReport(jReport, parametros, jrds);

                //if (!(jViewer == null)) {
                //jViewer = new JasperViewer(jPrint, false);
                //jViewer.setExtendedState(JFrame.MAXIMIZED_BOTH);
                if (jPrint != null) {
                    jViewer.viewReport(jPrint, false);
                    jPrint = null;
                }
                //}

            } catch (Exception ex) {
                ex.printStackTrace();
            }

        }
    }//GEN-LAST:event_jbImprimirActionPerformed
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
    public void run() {
    new jfVisualizarInformacoesCmei().setVisible(true);
    }
    });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbFechar;
    private javax.swing.JButton jbImprimir;
    private javax.swing.JComboBox jcbNomeEntidade;
    private javax.swing.JLabel jlbNrAlunosBercario;
    private javax.swing.JLabel jlbNrAlunosMaternal;
    private javax.swing.JLabel jlbNrAlunosPre;
    private javax.swing.JLabel jlbNrAlunosTotal;
    private javax.swing.JLabel jlbNrEstagiariosBercario;
    private javax.swing.JLabel jlbNrEstagiariosMaternal;
    private javax.swing.JLabel jlbNrEstagiariosPre;
    private javax.swing.JLabel jlbNrEstagiariosTotal;
    private javax.swing.JLabel jlbNrMonitoresBercario;
    private javax.swing.JLabel jlbNrMonitoresMaternal;
    private javax.swing.JLabel jlbNrMonitoresPre;
    private javax.swing.JLabel jlbNrMonitoresTotal;
    private javax.swing.JLabel jlbNrProfessoresBercario;
    private javax.swing.JLabel jlbNrProfessoresMaternal;
    private javax.swing.JLabel jlbNrProfessoresPre;
    private javax.swing.JLabel jlbNrProfessoresTotal;
    private javax.swing.JLabel jlbNrSalasBercario;
    private javax.swing.JLabel jlbNrSalasMaternal;
    private javax.swing.JLabel jlbNrSalasPre;
    private javax.swing.JLabel jlbNrSalasTotal;
    private javax.swing.JPanel jpBotoes;
    private javax.swing.JPanel jpInformacoesCmei;
    private javax.swing.JPanel jpQuantitativo;
    private javax.swing.JTable jtbVisualizarQuadroPessoal;
    private javax.swing.JTextField jtfCapacidadeAlunos;
    private javax.swing.JTextField jtfCoordenador;
    private javax.swing.JTextField jtfEstagiarios;
    private javax.swing.JTextField jtfNumeroLotacoes;
    private javax.swing.JTextField jtfServidoresConcursados;
    private javax.swing.JTextField jtfVagasDisponiveis;
    // End of variables declaration//GEN-END:variables

//Outros Metodos ===========================================================================================================================================
    public void fechar() {
        this.dispose();
    }

    public void cancelar() {

        DefaultTableModel modelo = (DefaultTableModel) jtbVisualizarQuadroPessoal.getModel();

        setCamposParaZero();

        modelo.setRowCount(0);

    }

    public void preencheComboCmeis() {

        DAO dao = new DAO();
        List listaCmeis = new ArrayList();

        jcbNomeEntidade.removeAllItems();
        jcbNomeEntidade.addItem("");

        listaCmeis = dao.listarCmeis();

        for (int i = 0; i < listaCmeis.size(); i++) {
            jcbNomeEntidade.addItem(listaCmeis.get(i));
        }
    }

    public void desabilitaCampos() {

        jtfCapacidadeAlunos.setEditable(false);
        jtfCoordenador.setEditable(false);
        jtfEstagiarios.setEditable(false);
        jtfNumeroLotacoes.setEditable(false);
        jtfServidoresConcursados.setEditable(false);
        jtfVagasDisponiveis.setEditable(false);

    }

    public void buscaCmei() {

        DAO dao = new DAO();
        Cmei cmei;
        int codigoAux;

        cmei = (Cmei) dao.buscaCmei((String) jcbNomeEntidade.getSelectedItem(), "", "", "");

        jtfCapacidadeAlunos.setText(cmei.getCapacidadeAlunos());
        jtfCoordenador.setText(cmei.getCoordenadorAtual());
        jtfEstagiarios.setText("" + cmei.getNumeroEstagiarios());
        jtfNumeroLotacoes.setText("" + cmei.getNumeroLotacoes());
        jtfServidoresConcursados.setText("" + (cmei.getNumeroLotacoes() - cmei.getNumeroEstagiarios()));
        jtfVagasDisponiveis.setText("" + cmei.getVagasDisponiveis());

        codigo = cmei.getCodigoCmei();

    }

    public void buscaQuadroPessoal() {

        DefaultTableModel modelo = (DefaultTableModel) jtbVisualizarQuadroPessoal.getModel();
        DAO dao = new DAO();
        Servidor serv;
        List listaServidores = new ArrayList();

        listaServidores = (List) dao.listarServidores(jcbNomeEntidade.getSelectedItem().toString());

        modelo.setRowCount(0);

        for (int i = 0; i < listaServidores.size(); i++) {

            serv = (Servidor) listaServidores.get(i);

            modelo.addRow(new String[]{String.valueOf(serv.getNomeServidor()), String.valueOf(serv.getFuncaoCargo()), String.valueOf(serv.getModalidade()), String.valueOf(serv.getMatricula())});

        }

        if (jtbVisualizarQuadroPessoal.getRowCount() > 0) {
            jtbVisualizarQuadroPessoal.getSelectionModel().setSelectionInterval(0, 0);
        }

    }

    public void buscaQuantitativos() {

        DAO dao = new DAO();
        Cmei cme;

        int nrSalasBercario;
        int nrSalasMaternal;
        int nrSalasPre;

        cme = (Cmei) dao.buscaCmei(jcbNomeEntidade.getSelectedItem().toString(), "", "", "");

        nrSalasBercario = cme.getNumeroSalasBercarios();
        nrSalasMaternal = cme.getNumeroSalasMaternal();
        nrSalasPre = cme.getNumeroSalasPre();

        jlbNrSalasBercario.setText("" + nrSalasBercario);
        jlbNrSalasMaternal.setText("" + nrSalasMaternal);
        jlbNrSalasPre.setText("" + nrSalasPre);
        jlbNrSalasTotal.setText("" + (nrSalasBercario + nrSalasMaternal + nrSalasPre));

        jlbNrAlunosBercario.setText("" + dao.getQuatitativoAlunos("BERÇÁRIO", "MATRICULA", (String) jcbNomeEntidade.getSelectedItem()));
        jlbNrAlunosMaternal.setText("" + dao.getQuatitativoAlunos("MATERNAL", "MATRICULA", (String) jcbNomeEntidade.getSelectedItem()));
        jlbNrAlunosPre.setText("" + dao.getQuatitativoAlunos("PRÉ", "MATRICULA", (String) jcbNomeEntidade.getSelectedItem()));
        jlbNrAlunosTotal.setText("" + dao.getQuatitativoAlunos("", "MATRICULA", (String) jcbNomeEntidade.getSelectedItem()));

        jlbNrMonitoresBercario.setText("" + dao.getQuantitativoServidores("BERÇÁRIO", (String) jcbNomeEntidade.getSelectedItem(), "MONITOR(A)", "CONCURSADO/CONTRATADO", 0, 0));
        jlbNrMonitoresMaternal.setText("" + dao.getQuantitativoServidores("MATERNAL", (String) jcbNomeEntidade.getSelectedItem(), "MONITOR(A)", "CONCURSADO/CONTRATADO", 0, 0));
        jlbNrMonitoresPre.setText("" + dao.getQuantitativoServidores("PRÉ", (String) jcbNomeEntidade.getSelectedItem(), "MONITOR(A)", "CONCURSADO/CONTRATADO", 0, 0));
        jlbNrMonitoresTotal.setText("" + dao.getQuantitativoServidores("", (String) jcbNomeEntidade.getSelectedItem(), "MONITOR(A)", "CONCURSADO/CONTRATADO", 0, 0));

        jlbNrEstagiariosBercario.setText("" + dao.getQuantitativoServidores("MATERNAL", (String) jcbNomeEntidade.getSelectedItem(), "ESTAGIÁRIO(A)", "CONCURSADO/CONTRATADO", 0, 0));
        jlbNrEstagiariosMaternal.setText("" + dao.getQuantitativoServidores("BERÇÁRIO", (String) jcbNomeEntidade.getSelectedItem(), "ESTAGIÁRIO(A)", "CONCURSADO/CONTRATADO", 0, 0));
        jlbNrEstagiariosPre.setText("" + dao.getQuantitativoServidores("PRÉ", (String) jcbNomeEntidade.getSelectedItem(), "ESTAGIÁRIO(A)", "CONCURSADO/CONTRATADO", 0, 0));
        jlbNrEstagiariosTotal.setText("" + dao.getQuantitativoServidores("", (String) jcbNomeEntidade.getSelectedItem(), "ESTAGIÁRIO(A)", "CONCURSADO/CONTRATADO", 0, 0));

        jlbNrProfessoresBercario.setText("" + dao.getQuantitativoServidores("MATERNAL", (String) jcbNomeEntidade.getSelectedItem(), "PROFESSOR(A)", "CONCURSADO/CONTRATADO", 0, 0));
        jlbNrProfessoresMaternal.setText("" + dao.getQuantitativoServidores("BERÇÁRIO", (String) jcbNomeEntidade.getSelectedItem(), "PROFESSOR(A)", "CONCURSADO/CONTRATADO", 0, 0));
        jlbNrProfessoresPre.setText("" + dao.getQuantitativoServidores("PRÉ", (String) jcbNomeEntidade.getSelectedItem(), "PROFESSOR(A)", "CONCURSADO/CONTRATADO", 0, 0));
        jlbNrProfessoresTotal.setText("" + dao.getQuantitativoServidores("", (String) jcbNomeEntidade.getSelectedItem(), "PROFESSOR(A)", "CONCURSADO/CONTRATADO", 0, 0));

    }

//Geradores, Validadores===========================================================================================================================================
//Getters and Setters===========================================================================================================================================
    public String getNomeUsuario() {
        return nomeUsuario;
    }

    public void setNomeUsuario(String nomeUsuario) {
        this.nomeUsuario = nomeUsuario;
    }

    public void setCamposParaZero() {

        jtfCapacidadeAlunos.setText("0");
        jtfCoordenador.setText("");
        jtfEstagiarios.setText("0");
        jtfNumeroLotacoes.setText("0");
        jtfServidoresConcursados.setText("0");
        jtfVagasDisponiveis.setText("0");

        jlbNrSalasBercario.setText("0");
        jlbNrSalasMaternal.setText("0");
        jlbNrSalasPre.setText("0");
        jlbNrSalasTotal.setText("0");

        jlbNrAlunosBercario.setText("0");
        jlbNrAlunosMaternal.setText("0");
        jlbNrAlunosPre.setText("0");
        jlbNrAlunosTotal.setText("0");

        jlbNrMonitoresBercario.setText("0");
        jlbNrMonitoresMaternal.setText("0");
        jlbNrMonitoresPre.setText("0");
        jlbNrMonitoresTotal.setText("0");

        jlbNrEstagiariosBercario.setText("0");
        jlbNrEstagiariosMaternal.setText("0");
        jlbNrEstagiariosPre.setText("0");
        jlbNrEstagiariosTotal.setText("0");

        jlbNrProfessoresBercario.setText("0");
        jlbNrProfessoresMaternal.setText("0");
        jlbNrProfessoresPre.setText("0");
        jlbNrProfessoresTotal.setText("0");

    }
//Metodos DAO===========================================================================================================================================
}
